### ISSUE TITLE
Liquibase doesn't snapshot WHERE clause on SQL Server INDEX objects

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1228]
## Environment
**Liquibase Version**: 3.9.0, 3.8.7, 3.10.1

## Description
When running the "liquibase snapshot" or "liquibase generateChangeLog" against a SQL Server containing any indexes with the "WHERE" clause, liquibase does not capture that clause.

## Steps To Reproduce
1. Run the following changeSets with the "liquibase update" command:

```
create table employees3
(
    id          int,
    employee_id int,
    last_name   int,
    first_name  int,
    salary      int
);

 CREATE INDEX EmployeesOrders1 ON dbo.employees3 
 (  
 	employee_id ASC,  
	last_name ASC,
	first_name ASC,
	salary ASC
 )  
WHERE employee_id=1
```

1. Run: "liquibase snapshot" or "liquibase generateChangeLog"

## Actual Behavior
The resulting snapshot/changeLog will contain incorrect INDEX EmployeesOrders1:

```
    <changeSet author="Administrator (generated)" id="1594220066963-16">
        <createIndex indexName="EmployeesOrders1" schemaName="dbo" tableName="employees3">
            <column computed="true" name="([employee_id]=(1))"/>
            <column computed="true" name="([employee_id]=(1))"/>
            <column computed="true" name="([employee_id]=(1))"/>
            <column computed="true" name="([employee_id]=(1))"/>
        </createIndex>
    </changeSet>
```

And here's the updateSql result:

```
-- Changeset db.changelog-1.0.xml::1594220066963-16::Administrator (generated)
CREATE NONCLUSTERED INDEX EmployeesOrders1 ON employees3(([employee_id]=(1)), ([employee_id]=(1)), ([employee_id]=(1)), ([employee_id]=(1)))
GO
```

## Expected/Desired Behavior
The resulting snapshot/changeLog should contain correct description of INDEX object EmployeesOrders1 and any other indexes that have the "WHERE" clause.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-340) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

**Comment by nvoxland** [comment]
Are both of those indexes being created at the same time as part of the issue?

Or are you creating just one index or the other?

Asking, because they are both on the same table and the same columns, so liquibase sees them as the same index in comparisons. So if you are making both indexes, you'll only get one in a diffChangeLog not because of the WHERE clause, but because of it being a duplicate index.

**Comment by nvoxland** [comment]
We are going to close this issue as "won't fix".

Liquibase does not currently have a way to represent a "where" clause in createIndex, and it is a database-specific enough feature that we have no plans of adding it right now.

The error occurs because the "where" metadata comes through in the same column of the mssql metadata that it stores something like:
```
CREATE INDEX EmployeesOrders1 ON dbo.employees3 
( lower(last_name) );
```

which we do support by having name="lower(last_name)".

We could do the work of figuring out how to tell from the sqlserver metadata when the filter_criteria metadata column is from a where clause and when it's a computed column, which would allow us to just ignore the "where" part and get XML like this:

```
        <createIndex indexName="EmployeesOrders1" tableName="employees3">
            <column name="employee_id"/>
            <column name="last_name"/>
            <column name="first_name"/>
            <column name="salary"/>
        </createIndex>
```

But that is STILL not respecting the where clause, it's just not respecting it in a different way. So it's not like it "fixed" the bug. It does "fix" it so the generated index XML can run successfully, but that just hides the problem a bit more.

I will add a message of `The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed` that gets output when running diffChangeLog/generateChangeLog to help remind people that the generated changeSets can be wrong. This is an example of when.
