### ISSUE TITLE
executeCommand changeSet fails on >=3.10.1

### ISSUE THREAD

**Issue by chas-mafli** [liquibase/liquibase#1378]
## Environment
**Liquibase Version**: >=3.10.1

**Liquibase Integration & Version**: ant

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MariaDB 10.3

**Operating System Type & Version**: Debian Stretch

## Description
A changeSet with only a `<executeCommand>` statement fails in >=3.10.1, it works under 3.10.0.

```
Unable to update database. liquibase.exception.MigrationFailedException: Migration failed for change set liquibase.xml::xxxx::xxxx:
     Reason: java.lang.ClassCastException: liquibase.database.jvm.JdbcConnection cannot be cast to com.datical.liquibase.ext.database.jvm.ProJdbcConnection
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:659)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:97)
        at liquibase.Liquibase.update(Liquibase.java:201)
        at liquibase.Liquibase.update(Liquibase.java:178)
        at liquibase.Liquibase.update(Liquibase.java:328)
        at liquibase.integration.ant.DatabaseUpdateTask.executeWithLiquibaseClassloader(DatabaseUpdateTask.java:34)
        at liquibase.integration.ant.BaseLiquibaseTask.execute(BaseLiquibaseTask.java:88)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: java.lang.ClassCastException: liquibase.database.jvm.JdbcConnection cannot be cast to com.datical.liquibase.ext.database.jvm.ProJdbcConnection
        at com.datical.liquibase.ext.SqlPlusRunner.buildConnectionString(Unknown Source)
        at com.datical.liquibase.ext.SqlPlusRunner.createFinalCommandArray(Unknown Source)
        at liquibase.change.core.ExecuteShellCommandChange.generateStatements(ExecuteShellCommandChange.java:142)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1256)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:622)
        ... 36 more
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-637) by [Unito](https://www.unito.io/learn-more)

**Comment by chas-mafli** [comment]
Ok this seems to occur in some cases for 3.10.0 too but not 3.9.0. I'm using `<antcall>` in my build.xml and I can avoid this error by specifying `inheritAll="true"` in some cases... but not in all :/ So perhaps it's ant related but can't make any sense of it.

**Comment by molivasdat** [comment]
Hi @chas-mafli Can you provide your changelog that produces this error?

**Comment by mattbertolini** [comment]
@chas-mafli Also, can you provide a snippet of the ant configuration for liquibase? I'm looking for how the `<database>` element is configured and how the classpath is set up for the task, but the whole thing would be helpful. I'm curious about the `inheritAll="true"` making it work sometimes. `inheritAll="true"` means Ant is passing all properties to the new ant project being created with `<antcall>`. I'm insterested in what properties are set that potentially make this work (something like the classpath since this is a `ClassCastException`. Finally, I've noticed it's trying to cast it over to a Liquibase Pro type so I want to make sure that is what is desired. Are you using liqubase pro?

**Comment by chas-mafli** [comment]
@molivasdat it just looks like this (some things omitted)

```xml
<changeSet author="xxx" context="xxxx" id="xxxxx">
    <executeCommand executable="php">
        <arg value="${basedir}/database/xxxxx.php" />
        <arg value="-e" />
        <arg value="${app.env}" />
    </executeCommand>
</changeSet>
```

@mattbertolini the offending part looks like this

```xml
<updateDatabase
    changeLogFile="${database.changelog}"
    classpathref="class.path"
    contexts="${liquibase.contexts}">
    <changeLogParameters>
        <changeLogParameter name="preinit" value="${liquibase.preinit}"/>
        <changeLogParameter name="app.env" value="${app.env}"/>
        <changeLogParameter name="basedir" value="${basedir}"/>
    </changeLogParameters>
    <database driver="${database.driver}" url="${database.url}"
        user="${app.db.user}" password="${app.db.password}"/>
</updateDatabase>
```

Now I can't seems to reproduce this `inheritAll="true"` thing so perhaps I was just confused. I've had much back and forth with this thing so I'm a little puzzled haha. I'm using `inheritRefs="true"` though just to be clear.

But yeah no I'm not using pro so my thinking it should never try to use `ProJdbcConnection`?

**Comment by chas-mafli** [comment]
Perhaps it has something to do with an `<antcall>` to a target with its own antcalls, i.e. nested antcalls. Because the target that antcalls the update target works fine directly from the ant cli but targets that uses that target with antcall produces this error it seems.

**Comment by mattbertolini** [comment]
@chas-mafli It may have something to do with `<antcall>` in combination with the usage of the `classpathref` attribute. The `<antcall>` task does not inherit references by default and the `classpathref` is using a reference so it's probably not getting the desired classpath to the `updateDatabase` task. You can inherit references in `<antcall>` by setting the `inheritRefs=true` attribute as well as the `inheritAll=true` flag for properties [0].

I would try that and see if anything changes. Report back and we can take a look further.

[0] https://ant.apache.org/manual/Tasks/antcall.html

**Comment by mattbertolini** [comment]
Hmm. Nested `<antcall>`s can be a tricky business. For this to work you will need to set `inheritAll="true"` and `inheritRefs="true"` on each `<antcall>` for the Liquibase task to work (but it sounds like you've done that already). 

Since you're not using pro, I'm a bit curious how the pro jar is getting onto the classpath? How exactly are you creating the classpath defined with id `class.path`? Could you output the path by doing something like `<echo>${toString:class.path}</echo>` in the ant file near the `updateDatabase` task? I'm guessing that if the pro jar is no longer on the classpath then the exception will go away since there is nothing to cast to. I don't have any pro experience myself so I'm not sure how that class would be loaded. It seems like it would be detected dynamically if it's found on the classpath. Perhaps a liquibase dev could clarify that.

If the liquibase task works directly with the ant cli I'm hesitant to say there is a bug but there may be some areas to improve the ant tasks if we can find out what is causing the exception (and the presence of the pro jar).

**Comment by chas-mafli** [comment]
I just download the jar here from github and put it on my classpath so there's nothing weird on it really.

I did some more tests and now it seems like on 3.10.0 it fails in this way with nested antcalls but on >=3.10.1 it fails even if the antcalls aren't nested.

**Comment by chas-mafli** [comment]
Ok so I ran Java 8 before and now I tested on 11 and it fails with unnested and nested calls on 3.10.0 and on >=3.10.1 it works with unnested calls but fails with nested... the other way around that is :/

**Comment by mattbertolini** [comment]
Thanks for this info! It's helped me learn a bit more. I've downloaded the same jar you did and examined its contents. I found the pro classes contained in the jar. I had no idea they were there so I definitely learned something. 

Here's what I've figured out about the error:

```
Caused by: java.lang.ClassCastException: liquibase.database.jvm.JdbcConnection cannot be cast to com.datical.liquibase.ext.database.jvm.ProJdbcConnection
        at com.datical.liquibase.ext.SqlPlusRunner.buildConnectionString(Unknown Source)
        at com.datical.liquibase.ext.SqlPlusRunner.createFinalCommandArray(Unknown Source)
        at liquibase.change.core.ExecuteShellCommandChange.generateStatements(ExecuteShellCommandChange.java:142)
```

When I look at the `ExecuteShellComamndChange` class I can clearly see it's designed to be subclassed and that is exactly what `SqlPlusRunner` does. Now I don't entirely know why `SqlPlusRunner` is selected over the `ExecuteShellComamndChange` class but I think it probably has something to do with Liquibase's priority system for service loading. The `ExecuteShellComamndChange` class has a default priority but I don't know what `SqlPlusRunner`'s priority is as I don't have the source code for pro. Since the `SqlPlusRunner` is clearly selected we can assume it's priority is higher.

It's the `SqlPlusRunner` class that tries to cast the `JdbcConnection` to a `ProJdbcConnection` which is definitely not possible right now in the ant tasks as they are not aware of pro classes and don't create them.

One possible way to fix this would be to check to see if the class can be cast before performing the cast. Another possible fix is to not load the pro classes when pro is not requested. Another option is to enhance the Ant tasks to be pro-aware (have some sort of boolean flag that can be toggled). All of these fixes are outside of my abilities as I don't have access to the pro codebase.

And all of this is even more confusing since you say that it sometimes works! That one I'm still baffled by. My only hunch on that is the nested `<antcalls>` are messing with the classpath order and classloaders so that _sometimes_ the pro classes are loaded later and therefore not found so Liquibase can select the regular `ExecuteShellComamndChange` class.

@molivasdat Do you have any thoughts on this?

**Comment by chas-mafli** [comment]
@mattbertolini ah so you could reproduce it yourself at least!

The "sometimes works" was before I saw this antcall pattern and the fact that 3.9.0, 3.10.0 and >=3.10.1 all behaved differently which of course added to the confusion.

**Comment by molivasdat** [comment]
@mattbertolini and @chas-mafli I am just as puzzled on the intermittent differences.  I'll check internally with the folks that have access to Pro and see what I can find.  May be next week until I can get back to it.

**Comment by mattbertolini** [comment]
I'm not sure but I might I'm on to something. I spent some more time investigating last night and I do see a discrepancy on how the Ant tasks create the `DatabaseConnection` and how other integrations do (like the CLI). 

The Ant tasks create the `JdbcConnection` manually via the `DatabaseFactory.findCorrectDatabaseImplementation()` method passing an already created `JdbcConnection` object. In other integrations, the `DatabaseFactory.openDatabase()` method is called which creates the connection object itself. There is much more sophisticated logic around selecting the proper connection type in this `DatabaseFactory` (via the `ConnectionServiceFactory`). This may explain why the Ant tasks are unaware of the pro connection types. 

I am going to dig a little more and see if this affects the exception. I will hopefully have more information soon. Regardless of whether this fixes the problem, that is definitely something to change.

**Comment by molivasdat** [comment]
Hi @chas-mafli 
One of our developers took a look at this and used this as an example and worked for him.
```
<project name="liquibase-test" default="update" basedir="." xmlns:liquibase="antlib:liquibase.integration.ant">
  <target name="prepare">
    <path id="classpath">
      <pathelement location="lib"/>
      <fileset dir="lib/">
        <include name="*.jar"/>
      </fileset>
    </path>
    <taskdef resource="liquibase/integration/ant/antlib.xml" uri="antlib:liquibase.integration.ant">
      <classpath refid="classpath"/>
    </taskdef>
    <!-- set global properties for this build -->
    <property name="db.url" value="jdbc:oracle:thin:@localhost:1521/BUCKET_01"/>
    <property name="db.user" value="username"/>
    <property name="db.pass" value="password"/>
    <liquibase:database id="my-database" url="${db.url}" user="${db.user}" password="${db.pass}" driver="oracle.jdbc.OracleDriver"/>
  </target>
  <target name="default" depends="prepare" >
    <antcall target="update" inheritrefs="true">
    </antcall>
  </target>
  <target name="update">
    <liquibase:updateDatabase 
      changeLogFile="oracle_lbpro_master_changelog.xml"
      classpathref="classpath"
      labels="setup,shell">
      <database driver="oracle.jdbc.OracleDriver" url="${db.url}" user="${db.user}" password ="${db.pass}"/>
    </liquibase:updateDatabase>
  </target>
</project>
```
Would this work for you?

**Comment by mattbertolini** [comment]
Following up on my comment from few days ago. I'm thinking the exception was intermittent because of race condition loading data in the `DatabaseFactory` and `ConnectionServiceFactory`. I no longer think it has to do with `<antcall>` issues since I can sometimes cause the issue in my debugger. 

I have opened a PR (#1427) to change the Ant tasks to properly leverage the `DatabaseFactory` like the other integrations do. This should make the connection creation logic a lot more predicable and properly support pro connection types if desired. I'm fairly confident this will solve the issue but at the very least, it will bring the Ant tasks in line with the rest of the codebase.

**Comment by chas-mafli** [comment]
@molivasdat tried that example and it works fine with 3.9.0 but gets the same cast exception on 3.10.2 like before.

@mattbertolini doesn't seem like a race condition to me seeing as I could reproduce it without fail again with @molivasdat example? Though it sounds like your PR there should fix it I guess. Don't think I have time to test it though (well compile it and all that jazz that is).
