### ISSUE TITLE
Usage of endDelimiter in scripts now require spacing

### ISSUE THREAD

**Issue by kraymondksc** [liquibase/liquibase#1623]
## Environment
**Liquibase Version**: 3.10.3

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MySQL

**Operating System Type & Version**: OSX 10.15.7

## Description
We are in the process of upgrading Liquibase from 3.3.1 to 3.10.3.  The following worked correctly in 3.3.1. 

We have stored procedures that are created via Liquibase.  Given the following changeset definition:
`<changeSet author="xxx" id="123" runOnChange="true">
         <sqlFile path="xxx/xxx/db/changelog/stored_procedures/xxx/storedProcedure.sql" relativeToChangelogFile="false" endDelimiter="\$\$" />
</changeSet>`

Liquibase fails on the following line:
`DELIMITER $$

DROP PROCEDURE IF EXISTS storedProcedure$$`

If we modify the statement to have a space between the stored procedure name and end delimiter it works correctly.
`DELIMITER $$

DROP PROCEDURE IF EXISTS storedProcedure $$`

## Steps To Reproduce
List the steps to reproduce the behavior.
We are executing Liquibase using the liquibase-maven-plugin

## Actual Behavior
Statements executed where there is no space between a statement and the end delimiter fail with the following error:
`[ERROR] Error setting up or running Liquibase:
[ERROR] Migration failed for change set storedProcedure.xml::123::xxx:
[ERROR]      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE PROCEDURE at line 3 [Failed SQL: (1064) DROP PROCEDURE IF EXISTS storedProcedure$$`

## Expected/Desired Behavior
MySQL allows no spacing between and end delimiter and statement so we feel that this functionality should be restored

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1102) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @kraymondksc Thanks for writing up this issue.  We will add it to the list of issues that we are processing.

**Comment by nvoxland** [comment]
The reason the problem comes up now is because we 3.10 we use a smarter, tokenizing parser for splitting vs. the simple string regular expression we had in 3.3. That lets us do things like "it doesn't split on $$'s that occur inside comments or strings".

Unfortunately, the tokenizing happens on spaces, so we now see a token as `DELIMITER$$` and our "is X a delimiter" is checking "does it completely match "$$" fails on that. The space makes it see it as two separate tokens and it correctly identifies the delimiter".

I don't think we can easily change the tokenizing logic, because there are databases with tokens that end with $'s and we need to respect that too.

The easiest fix for you may be to just remove the `DELIMITER$$` lines from all your scripts. Liquibase doesn't actually need it, since we use the endDelimiter attribute to know how to split statements. We'd just be passing the DELIMTER statement to the underlying database which just ignores it since the database doesn't care either. It's just the mysql client that uses DELIMITER.

**Comment by kraymondksc** [comment]
Thanks for taking a look.  We have a few different options to move forward with given that this only happens with a handful of our scripts.
