### ISSUE TITLE
modifyDataType does not preserve nullability on MSSQL

### ISSUE THREAD

**Issue by Vampire** [liquibase/liquibase#1763]
## Environment
**Liquibase Version**: 3.6.3

**Liquibase Integration & Version**: n/a

**Liquibase Extension(s) & Version**: n/a 

**Database Vendor & Version**: MSSQL

**Operating System Type & Version**: n/a

## Description
If you do an `addNotNullConstraint` on a column and then use `modifyDataType` on the same column, the not null constraint does not carry over on MSSQL. On Oracle this works fine. MSSQL should also preserver the nullability of a column.

**Comment by molivasdat** [comment]
Hi @Vampire Thanks for writing up this issue.  Can you provide a changeset example that exemplifies the error?
Does this fail the same on v4.3.1?

**Comment by Vampire** [comment]
```xml
   <changeSet id="xxx" author="n/a">
      <modifyDataType
            columnName="NAME"
            newDataType="VARCHAR(80)"
            tableName="MY_TABLE"/>
   </changeSet>
```
where `NAME` has a not-null constraint before and lost it after.

**Comment by smith-xyz** [comment]
Hi @Vampire, this is interesting, never noticed this before but it seems SQL Server expects explicit casting of Null when changing the datatype of a column. I think this is done because SQL Server wants to know how changing the datatype should handle null vs not null given that the type has changed. I'm not entirely sure why Oracle will preserve the null check. Maybe some kind of config, not really sure. I probably just don't know enough to make a judgement (please, anyone, feel free to fill in my knowledge gap!).

Here is the SQL I'm using in my databases to see how each executes:  
``` SQL
--mssql
CREATE TABLE TestTable (Name varchar(50) NOT NULL);

SELECT COLUMNPROPERTY(OBJECT_ID('dbo.TestTable', 'U'), 'Name', 'AllowsNull');

ALTER TABLE TestTable ALTER COLUMN Name varchar(250);

SELECT COLUMNPROPERTY(OBJECT_ID('dbo.TestTable', 'U'), 'Name', 'AllowsNull');

ALTER TABLE TestTable ALTER COLUMN Name varchar(250) NOT NULL;

SELECT COLUMNPROPERTY(OBJECT_ID('dbo.TestTable', 'U'), 'Name', 'AllowsNull');

Drop Table TestTable;


--oracle
CREATE TABLE LIQUIBASE.TestTable (Name VARCHAR2(50) NOT NULL);

select nullable from all_tab_columns where owner = 'LIQUIBASE' and table_name = 'TESTTABLE' and column_name = 'NAME';
   
ALTER TABLE LIQUIBASE.TestTable MODIFY Name VARCHAR2(250);

select nullable from all_tab_columns where owner = 'LIQUIBASE' and table_name = 'TESTTABLE' and column_name = 'NAME';

Drop Table LIQUIBASE.TestTable;
```

Liquibase executes it much the same, Oracle's SQL does not add anything additional to specify the not null, as mentioned it is preserved by the database.

Given that the two databases seems to hold some responsibility in whether they preserve the null check on a datatype change, think this would be more of an enhancement for liquibase to grab the columns null check info to assist in determining whether to add 'NOT NULL' to the end of the alter statement in the case of a SQL Server instance. Haven't tested with other databases yet, not sure if others also lose the null check when the datatype is modified.

**Comment by FBurguer** [comment]
Closing this issue, we are continue to look into it on issue #3245

**Comment by Vampire** [comment]
@FBurguer just to be sure, are you aware that this issue is about MSSQL while the other is about MySQL?
