### ISSUE TITLE
Liquibase not adjusting databasechangeloglock table when incompatible

### ISSUE THREAD

**Issue by donggyu04** [liquibase/liquibase#1780]
## Description
When I  bump the Liquibase version up 2.0.5 to 3.5.3 and run application, liquibase failed with logs below.

```
Caused by: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = TRUE,  WHERE ID = 1 AND LOCKED = FALSE: Value too long for column "LOCKED CHAR(1) NOT NULL": "'TRUE' (4)"; SQL statement:
```

> **LOCKED = FALSE: Value too long for column "LOCKED CHAR(1) NOT NULL": "'TRUE' (4)";**

It seems to be a problem caused by changing the schema of the LOCKED column in the DATABASECHANGELOGLOCK table as the version goes up.

Is any graceful or recommended solution to resolve this issue?
Thanks in advance.

## Steps To Reproduce
Run the Liquibase-core 2.0.5 before and run 3.5.3 with additional changelogs.

**Comment by molivasdat** [comment]
Hi @donggyu04, yes there is typically backwards compatibility up to a point.  2.0.5 was released in May 2012 and 3.5.3 was released Oct 2016.   It looks like there was a change in the schema definition of the databasechangeloglock table between those releases.  I'll get with the team to see how to migrate.

**Comment by nvoxland** [comment]
Yes, we do always try to be backwards compatible but sometimes miss things.

We have code to adjust the `databasechangelog` table if it is not compatible, but we don't currently have one with the databasechangeloglock` table (even in 4.3) because it has changed so infrequently. I don't think the actual structure has ever really changed, it's just that there was maybe a change in how we handle "boolean" types in the database you are using from storing T/F strings to true/false somewhere along the way. 

That makes it tricky to handle because even if/when we check the structure of the databasechangeloglock table, we want to respect differences in the "standard" version vs. what the database has while still fixing times when they are not compatible. Like if we need that to be a varchar(10) and you have it as varchar(1) we should fix it but if it's varchar(20) we would just leave it.

**To fix the problem, you can manually update your databases to have a large enough "locked" column. The easiest way is just to `drop table databasechangeloglock` and the next time liquibase runs it will recreate it correctly for you.**

Because that type has been stable for so long and so not affecting many people, it will probably be a while until we get to actually auto-fixing old databasechangeloglock table formats. There is an upcoming effort to clean up the lock service in general, so that is the point it probably makes sense to address.

**Comment by FBurguer** [comment]
We are looking on a larger fix for similiar issues for `DATABASECHANGELOGLOCK` table generation. Closing this issue
