### ISSUE TITLE
Can't insert an empty blob with loadData in ORACLE 

### ISSUE THREAD

**Issue by kuhjunge** [liquibase/liquibase#1811]
## Environment
**Liquibase Version**: 3.8.5

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: Oracle Database 19c (19.3.0)

**Operating System Type & Version**: Linux

## Description
It is not possible, to insert empty string blobs via loadData in oracle, because oracle does not allow NULL as insert value. Liquibase uses probably something like utl_raw.cast_to_raw('') to convert strings to a blob but this function does not allow an empty string. The same changelog works fine with mssql.

## Steps To Reproduce
Execute following Changelog:

Creating the Table:

```
<property dbms="oracle,firebird" global="true" name="Domain.Blob" value="blob"/>
<property dbms="oracle,firebird" global="true" name="Domain.Counter" value="integer"/>
 <property dbms="mssql" global="true" name="Domain.Blob" value="image"/>
<property dbms="mssql" global="true" name="Domain.Counter" value="int"/>
    <changeSet author="Kuhjunge" context="schema-create" id="2e40e2d2-4704-4b37-ab6c-a291ded63462" objectQuotingStrategy="LEGACY">
        <createTable tableName="TABLEWITHBLOBS ">
            <column name="ID" type="${Domain.Counter}">
                <constraints primaryKey="true" primaryKeyName="XPKIGDATENBLOBS"/>
            </column>
            <column name="DATEN" type="${Domain.Blob}">
                <constraints nullable="false"/>
            </column>
        </createTable>
    </changeSet>
```

Insert the data

```
    <changeSet author="Kuhjunge" context="insert-data" id="insert-TABLEWITHBLOBS " objectQuotingStrategy="QUOTE_ALL_OBJECTS">
        <loadData commentLineStartsWith="#" encoding="UTF-8" file="TABLEWITHBLOBS .csv" quotchar="&quot;" relativeToChangelogFile="true" separator="," tableName="TABLEWITHBLOBS" usePreparedStatements="true">
            <column header="ID" name="ID" type="NUMERIC"/>
            <column header="DATEN" name="DATEN" type="BLOB"/>
        </loadData>
    </changeSet>
```

TABLEWITHBLOBS .csv:

```
"ID","DATEN"
"1","MTIzNDU2Nzg5MDEyMzQ1Njc4OTA="
"2",""
```

## Actual Behavior
Oracle SQL Exception: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: ORA-01400: Einfügen von NULL in ("SCHEMANAME"."TABLEWITHBLOBS "."DATEN") nicht möglich 

(Translation: Cannot insert NULL into ("SCHEMANAME"."TABLEWITHBLOBS "."DATEN")  )

I get the same result if I try to execute this SQL locally:

`INSERT INTO SCHEMANAME.TABLEWITHBLOBS (ID, DATEN) VALUES (2,utl_raw.cast_to_raw('')); `

## Expected/Desired Behavior
A empty blob will be inserted instead. Like with this command:

`INSERT INTO SCHEMANAME.TABLEWITHBLOBS (ID, DATEN) VALUES (3,EMPTY_BLOB()); `

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1528) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment]
Hi @kuhjunge Thanks for writing up this issue.  As a workaround to inserting empty blobs in the database can you make the column nullable?

**Comment by danielthegray** [comment]
I think that Oracle might handle "empty" things differently as well... Oracle's `VARCHAR` type will save `NULL` when given an empty string (which is why they created the `VARCHAR2` type, to have the normal/standard behavior), so I suspect something similar is happening here.

Another thing I find a bit strange, you say this problem happens on Liquibase 3.8.5... I see that your CSV data file has Base64 in the blob, which was only incorporated in version 3.10.x. Anyway, you can see how the BLOB data is decoded here:
https://github.com/liquibase/liquibase/blob/46fc9ce9ba08806d9ad943983cc99f4f9160aeb7/liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java#L135

Anyway, if I understand your request correctly, you essentially, want the "EMPTY_BLOB()" SQL command to be sent instead of the actual empty BLOB (which is being NULLed by Oracle)?

As you saw yourself,

    INSERT INTO SCHEMANAME.TABLEWITHBLOBS (ID, DATEN) VALUES (2,utl_raw.cast_to_raw('')); 

causes the same exception to be thrown. This is just another idiosyncrasy of Oracle. I personally don't see an easy way to change it to inject an SQL command from here, since at the referenced point in the code, it is only adding a parameter to the prepared statement (the root SQL query would have to be modified directly to include this EMPTY_BLOB() command for your proposal to work).

I think that one thing which could be of assistance would be the https://github.com/liquibase/liquibase/pull/944 where the PR author proposes to add a way to include "computed" values in a CSV file.

To make a long story short, I think your best bet is to set the column to NULLable for now. :)

**Comment by kuhjunge** [comment]
Okay, thank you for the information. 
The workaround with the NULLable column is working for me.
