### ISSUE TITLE
YAML changelog includeAll does not respect errorIfMissingorEmpty default false value

### ISSUE THREAD

**Issue by nadarian** [liquibase/liquibase#1897]
## Environment
**Liquibase Version**: 4.3.5

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Oracle 

**Operating System Type & Version**: Windows and Linux

## Description
If YAML master changelog an includeAll tag references a path that does not exist the error is thrown despite default for `errorIfMissingorEmpty` is false. Setting it explicitly to false also does not solve the problem.

## Steps To Reproduce
* Create a master-changelog.yaml file which references a directory that does not exist. For example:

```
databaseChangeLog:
  - includeAll:
      path: 075/
```

* Run an update
`liquibase --changelogFile=master-changelog.yaml update`

## Actual Behavior
An error is thrown

```
Unexpected error running Liquibase: Could not find directory or directory was empty for includeAll '075/'
For more information, please use the --logLevel flag
```

## Expected/Desired Behavior
Update should be executed successfully

I've also noticed that putting 
`errorIfMissingorEmpty` attribute in XML is not recognized anymore resulting in
`Attribute 'errorIfMissingorEmpty' is not allowed to appear in element 'includeAll'` error but this might be another issue.

**Comment by molivasdat** [comment]
Hi @nadarian Thanks for providing a very simple and elegant recreation scenario.  I was able to copy and paste your changelog and recreate the issue.
As a simple workaround you can use set the errorIfMissingorEmpty value like this until we are able to fix this.
```
databaseChangeLog:
  - includeAll:
      path: 075/
      errorIfMissingOrEmpty: false
```
We will add this to the issues we are processing.

**Comment by nvoxland** [comment]
The problem is that yaml/json/parser-code default to "true" for errorIfMissingOrEmpty in DatabaseChangeLog line 413, but xml has "false" as the default in the XSD, so that overrides the underlying default.

I can easily make that default change for yaml/json/custom, but that is going to be a change in behavior for anyone who is expecting includeAll to fail if the directory doesn't exist since that is how it has always worked.

So I think that at least needs the MajorRelease label with a "breaking change" notice in the release notes.

**ALTERNATELY:** I could take the default=false setting out of the 4.5.xsd which would bring XML in line with what yaml/json does, starting with anyone using the 4.5.xsd. This makes it more of a "when they are making a new file" type change, but would still be a behavior change for XML users.

I tend to think that from a usability standpoint, it should fail if the requested path doesn't exist rather than silently continue. People get confused when they ask for something and think it should work but they just have a typo or something. In that case, the bug is really in xml.

Thoughts?

**Comment by nvoxland** [comment]
NOTE: the `errorIfMissingOrEmpty` attribute was working for me in yaml, so this issue is purely about matching the defaults in yaml/json vs. xml.

**Comment by nvoxland** [comment]
After discussing the issue, we decided that it is better to fix XML to default to errorIfMissingOrEmpty="true".

I created #1960 to track that change.
