### ISSUE TITLE
logicalFilePath fails after upgrade from 3 to 4 when absolute path was previously used.

### ISSUE THREAD

**Issue by garethjevans** [liquibase/liquibase#2095]
## Environment

**Liquibase Version**:

4.4.3 (or any 4.x.x really)

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

MySQL 5.8 & Postgres 9.6 & 12

**Operating System Type & Version**:

MacOS & Ubuntu

## Description

After an upgrade from liquibase 3 to 4 we noticed that the CLI failed to detect that a migration script had already run.
- We were previously using absolute filepaths when using version 3
- We switched to loading these from the classpath
- We updated the logicalFilePath parameter to point to the original filepath
- When using v4, the logicalFilePath is modified and doesn't match the original

## Steps To Reproduce

List the steps to reproduce the behavior.
- Apply a changelog from an absolute path, e.g. /tmp/changelog.yaml with liquibase 3
- Upgrade to liquibase 4 and apply the the same changelog from a relative path, with /tmp/changelog.yaml

## Actual Behavior
You'll notice the second changelog gets applied too.  The logic to compare the filepaths in the database strips the leading `/` from the logicalFilePath e.g. `/tmp/changelog.yaml` != `tmp/changelog.yaml` so the changelog is applied twice.

## Expected/Desired Behavior
The second apply should not be applied.

## Additional Context
If the user sets a `logicalFilePath` in a changelog file then this should be used as is - and not modified before the comparison is done.

**Comment by molivasdat** [comment]
Hi @garethjevans Thanks for writing up this issue.  Yes there was a change from v3 to v4 to not include the fully qualified path to the files anymore.  A relative path is now used.  I'll check with development to see what the alternatives for you are.

**Comment by nvoxland** [comment]
Thanks, I'll take a look at the issue. 

The reason we don't do an exact "use the exact logicalFilepath" is because we add a layer of fuzzy matching to handle changes in behavior or bugs from earlier versions. Like if we had a release that was accidentally storing a `classpath:` prefix from spring boot we can know to ignore that. The `starts with /` vs `doesn't start with /` is something we should be handling in that fuzzy matching too but must not be completely.

If you update your logicalFilePath to not have the leading / in it, does it work for now?
