### ISSUE TITLE
tag-exists command requires --tag to be after it

### ISSUE THREAD

**Issue by twerthi** [liquibase/liquibase#2124]
## Environment

**Liquibase Version**: 4.5.0

**Liquibase Integration & Version**: Octopus Deploy Step Template

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description

The documentation shows that a command (update, updateSQL, etc...) is to be at the end of a command-line call.  The `tag-exists` command documentation shows that the `--tag=<tag>` needs to be after the command and does not work if it proceeds the `tag-exists` command.  I would expect that all `--` type arguments should precede the command as it is for all others.

## Steps To Reproduce

List the steps to reproduce the behavior.
This fails
& .\liquibase.bat --changeLogFile=db.changelog.xml --classpath=C:\liquibase-4.5.0\drivers\postgresql-42.2.24.jar --url=jdbc:postgresql://clusterpi.octopusdemos.app:5432/SAKILA_Liquibase --username=postgres --password=<SuperSecretPassword> --tag=runbook_deployment_tag tagExists  2>&1

This succeeds
& .\liquibase.bat --changeLogFile=db.changelog.xml --classpath=C:\liquibase-4.5.0\drivers\postgresql-42.2.24.jar --url=jdbc:postgresql://clusterpi.octopusdemos.app:5432/SAKILA_Liquibase --username=postgres --password=<Sp tag-exists --tag=runbook_deployment_tag 2>&1

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
The expected behavior is to allow the `--tag=<tag>` to be placed before the command

**Comment by twerthi** [comment]
@r2liquibase

**Comment by molivasdat** [comment]
HI @twerthi Thanks for alerting us to this issue. We will add this to the list of issues that we are processing.  Thanks for the detailed steps on how to reproduce this issue as well.

**Comment by nvoxland** [comment]
This is actually the expected behavior. The actual CLI pattern is `liquibase <global args> <command> <command-specific args>`. The global args are generally setting type things like `--file-encoding` and most of the arguments that normally need to be used fall into to the command-specific args section including ones like --username, --password, --url, etc.

So the "correct" way to be organizating your arguments is: 
```
& .\liquibase.bat tag-exists --changeLogFile=db.changelog.xml --classpath=C:\liquibase-4.5.0\drivers\postgresql-42.2.24.jar --url=jdbc:postgresql://clusterpi.octopusdemos.app:5432/SAKILA_Liquibase --username=postgres --password=<Sp  --tag=runbook_deployment_tag 2>&1
```

where the --tag argument is to the right of the command like all the other arguments.

For backwards-compatibility reasons we continue to support older arguments like --url, --username, --password etc. on either side, but for newer commands and newer arguments like `tag-exits --tag` we are better requiring the "correct" way.

We are still in the process of updating the doc pages to clean up old examples, but the goal is to eventually be more consistent and expected in where the various arguments go.
