### ISSUE TITLE
<loadData> cannot load columns of type "CLOB" into PostgreSQL

### ISSUE THREAD

**Issue by kontoeniki** [liquibase/liquibase#2158]
## Environment
**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: quarkus 2.3.1Final

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: postgres:13.1

**Operating System Type & Version**:

## Description
After upgrading from 4.3.5 to 4.4.3, liquibase dont load data from CSV-files, where a time column exists. If throws following exception:

CLOB resource not found

## Steps To Reproduce
```
<property name="clobType" value="longvarchar" dbms="h2"/>
<property name="clobType" value="clob" dbms="mysql, oracle, mssql, mariadb, postgresql"/>
```

```
<createTable tableName="crimereportdetails">
  <column name="id" type="bigint" autoIncrement="true">
    <constraints primaryKey="true" nullable="false" primaryKeyName="crimereportdetails_pkey"/>
  </column>
  <column name="description" type="${clobType}"/>
</createTable>
```

```
<loadData
  file="db/fake-data/crimereportdetails.csv"
  separator=";"
  tableName="crimereportdetails">
</loadData>
```

crimereportdeatils.csv

id;description
1;a serious crime
2;another serious crime
3;this is a test crime
4;null

## Additional Context
The loaddata works with h2 database but fails with postgressql

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-2161) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment]
Hi @kontoeniki Thanks for adding this issue.  We will add this to our list of issues to process.

**Comment by nvoxland** [comment]
The behavior you are seeing is the current/correct behavior. Whether it **should** be the current behavior is a different question we'll look at in the future, but changing the behavior gets to be a breaking change for a bunch of people regardless of what we do, and so we need to be very intentional on that.

There has been improvements in 4.6 with loadData, but the behavior with that version is to still correctly see that column as a clob and therefore treat the value in the CSV as the name of a file containing the possibly-large CLOB data. 

There was a set of releases where we stopped correctly recognizing the column as a clob in postgresql and treated it as a string and therefore as a simple value to insert. In 4.4 we fixed that bug, which made postgresql's loadData with clobs work like it did in older releases and also with most other databases with clobs, but still different than when it treated it as a string.

So, your adding of the type="string" is a perfectly correct answer to the problem. You are telling liquibase "the value to insert is just a string" so we use that logic vs. having to guess as what you want us to do by looking at the type of the column.
