### ISSUE TITLE
Postgres jdbc connection string is not properly parsed

### ISSUE THREAD

**Issue by alexandruantochi** [liquibase/liquibase#2205]
Running 

`liquibase history --url 'jdbc:postgresql://host:port/database?user=user&password=secret'` returns this error:

```
Starting Liquibase at 11:16:03 (version 4.5.0 #52 built at 2021-09-27 16:19+0000)
Liquibase Version: 4.5.0
Liquibase Community 4.5.0 by Datical
Unexpected error running Liquibase: Connection could not be created to jdbc:postgresql://host:port/database?user=user with driver org.postgresql.Driver.  The server requested password-based authentication, but no password was provided.

For more information, please use the --log-level flag
'password' is not recognized as an internal or external command,
operable program or batch file.
```

Looks like the `&` splits the url connection string into 2, making `password` a command. As per [jdbc](https://jdbc.postgresql.org/documentation/80/connect.html) and [liquibase](https://docs.liquibase.com/workflows/database-setup-tutorials/postgresql.html) documentation, the connection string should work like that

PS: this would work if using `--user` and `--password` prams separately and not including them in the URL

**Comment by molivasdat** [comment]
Hi @alexandruantochi Are you running this on windows or linux.  Depending on the OS using single quote or double quote may be necessary so that the command line interpreter of the OS does not interpret the & sign.  This is not a Liquibase issue.  This why the password parameter was placed in the properties file or passed separately as a parameter on the command line to avoid the OS catching and interpreting the & sign.
