### ISSUE TITLE
Can not user liquibase jar on commandline anymore

### ISSUE THREAD

**Issue by derfloDev** [liquibase/liquibase#2612]
## Environment

**Liquibase Version**: 4.8.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description

We have updated our liquibase versino from 4.5.0 to 4.8.0. Since the update we can not use the liquibase jar on the commandline anymore. We get the following error 'no main manigest attribute'.

## Steps To Reproduce

Run liqibase jar form command line

## Actual Behavior
Error  'no main manigest attribute'.

## Expected/Desired Behavior
Run the jar

**Comment by molivasdat** [comment]
@derfloDev Thanks for reporting this.  Looks like something changed between 4.5.0 and 4.6.1 to create this issue.

**Comment by molivasdat** [comment]
Simple way to test:
This works:
java -jar ~/liquibase4.5.0/liquibase.jar --version
This fails:
 java -jar ~/liquibase4.8.0/liquibase.jar --version
 no main manifest attribute, in ~/liquibase4.8.0/liquibase.jar

**Comment by nvoxland** [comment]
This is by design. 

You cannot specify both -jar and -cp in java, and users need an ability to control the classpath to run liquibase. They need to pick their drivers plus include all the required extra jars liquibase needs (pico, snakeyaml, etc.).

It's possible to hard-code classpath in the jar (like we did for a while), but that only really works if we know the directory structure of how users are running liquibase. Since we have no control over that, the guess we made was wrong more often than it was right.  

So rather than continuing to open people up to that confusion, we took out the settings that allowed -jar to work in favor of documenting the safer/better way to do it.

We have our liquibase/liquibase.bat script we ship with the CLI distribution which is the easiest way to run liquibase. That gets runs the specified/found version of java with a dynamically figured out classpath and an option for running with whatever other java arguments you want via the JAVA_OPTS env variable. So that script is usually the best route for people.

But, if you need the extra control of running java directly yourself, the main class is `liquibase.integration.commandline.LiquibaseCommandLine` so you can run `java -cp <set up your classpath> liquibase.integration.commandline.LiquibaseCommandLine <liquibase arguments>`

**Comment by nvoxland** [comment]
I could create a main-class setting in the MANIFEST.MF file that runs a class that just outputs a message on how we don't support `java -jar liquibase.jar` and how to run the launch script or use the LiquibaseCommandLine class. 

But, that could get in the way of people looking to build a custom liquibase.jar for their specific setup that can support java -jar since there'd be conflicting main-class entries when they create a union jar. 

I created Datical/liquibase-docs#138 as a start for improving the docs around starting liquibase

**Comment by JonathanBerkeley** [comment]
Documentation currently still says that running with "java -jar" is recommended over "java -cp":
https://docs.liquibase.com/workflows/liquibase-community/run-liquibase-without-launch-scripts.html
