### ISSUE TITLE
abosulte path of change log file given from tomcat context is not working and giving an issue that absolute path not supported from liquibase 4.0

### ISSUE THREAD

**Issue by up185014** [liquibase/liquibase#2658]
## Environment

**Liquibase Version**:  4.0.X all version 4.0.X all versions

**Operating System Type & Version**: windows 10

## Description
absolue path not supporting from 4.0 which causes an exception file not found.
abosulte path of change log file given from tomcat context is not working and giving an issue that absolute path not supported from liquibase 4.0.

## Steps To Reproduce

configure tomcat context like below
<Context>

    
	<Environment name="context.liquibase.changelog" override="false" type="java.lang.String" value="file:${catalina.home}/conf/liquibase/demo-changelog.xml"/>
	
</Context>
please change log file in same location and try to read.

## Actual Behavior

Issue with 4.x version which i can't see related issue with 3.10.3 for the path given to changelog file.
when upgrade to 4.x below issue coming.

Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:99)

## Expected/Desired Behavior

chane log file has to  be found and process file succesfully and all changes sets has to update into database.

## Additional Context

please resolve this issue, its thr since 4.x intial verison released.
have been asked many times to resolve it, but no solution given, and now same with 4.8.0. alos ,as vulnerabilities have come before 4.8.0 so has to move to 4.8.0 or latest but this relative path issue not leeting to move.

**Comment by up185014** [comment]
Hi team,

why there is no action on this item may i know please?

Thank you,
upendra parchuri.

**Comment by up185014** [comment]
@kataggart at least can u ask for workaround for the bug.we have to pick latest version as old version raised voulneribility.

**Comment by nvoxland** [comment]
Liquibase has always used the changelog file paths as being relative to a set of base locations to search (the search path). For tomcat, the default search path is "the web app's classpath". And so paths should be ideally listed relative to that. For example, if `${catalina.home}/conf/` is in the classpath (I think it is?) the value attribute should be `liquibase/demo-changelog.xml`. Because liquibase uses the changelog paths as part of the unique identifiers for each changeset, specifying an entire path like that will make for different seen paths on different environments where catalina.home may be different.

With 4.0 we did remove `/` from the default list of places to resolve paths from and one option for you could be to add `/` back to your application's classpath. There should be a way to configure that in tomcat? Then, your existing `file:${catalina.home}/conf/liquibase/demo-changelog.xml` path will work again because that path can be found within `/`. 

A probably-better fix is set your value to just `liquibase/demo-changelog.xml` and store it somewhere that is in the classpath. Because the path passed is part of the changeset identifiers, liquibase will see the new setting as meaning new changesets. You can address that by setting the `logicalFilePath` attribute in your changelog, or by updating the filepath value stored in the databasechangelog table. What is easiest will depend a lot on your particular setup.

A not-yet-released solution will be a new `searchPath` setting that will be available in 4.13.0 (#2917). With that change, the classpath and the searchPath are better separated and you can just set liquibase.searchPath to be `/` or whatever base location your changelog files are in.
