### ISSUE TITLE
SQL changeSet doesn't  honor "--precondition-change-log-property-defined"

### ISSUE THREAD

**Issue by kenyee** [liquibase/liquibase#2692]
## Environment
java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

**Liquibase Version**:
4.7.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Quarkus

**Liquibase Extension(s) & Version**: 
N.A.

**Database Vendor & Version**:
H2 but doesn't matter

**Operating System Type & Version**:
OSX

## Description

I expect the SQL not to be executed unless the env property is set to "test" (test environment) with this at the top of it:
--precondition-change-log-property-defined property:env value:test

## Steps To Reproduce
changeLog.xml:
```
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
          https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">

    <property name="env" value="${quarkus.profile}" />

    <include file="db/001-test-config.sql"/>
</databaseChangeLog>
```

001-test-config.sql looks like this at the top:
```
-- noinspection SqlNoDataSourceInspectionForFile

--liquibase formatted sql
--changeset testconfig:1
--precondition-change-log-property-defined property:env value:test
```

## Actual Behavior
SQL is executed for this changeset

## Expected/Desired Behavior
Changeset should not be executed if the execution environment is "test"

**Comment by tati-qalified** [comment]
I've verified that this is an issue in version 4.7.1 and in the latest 4.25.0. However, the [documentation](https://docs.liquibase.com/concepts/changelogs/preconditions.html#available-preconditions) doesn't provide a SQL example for `changeLogPropertyDefined`, so I don't believe it's supported. Using the precondition in the xml file works as expected.

I'll be closing this issue as it's expected behaviour, but feel free to let me know if you have any questions.
Thanks,
Tatiana
