### ISSUE TITLE
 liquibase-db2i startup error by creating database-change-log-table

### ISSUE THREAD

**Issue by tiran1984** [liquibase/liquibase#2727]
## Environment

**Liquibase Version**:
4.4.3
**Liquibase Integration & Version**: 
maven , quarkus
**Liquibase Extension(s) & Version**: 
[liquibase-db2i](https://github.com/liquibase/liquibase-db2i 4.4.3
**Database Vendor & Version**:
db2 AS400

## Description
At Startup we get an error 

Diese Tabelle wird versucht anzulegen BOOLEAN der Art *SQLUDT in *LIBL nicht gefunden. [Failed SQL: (-204) CREATE TABLE "WUYEDT2DVL".T350_GAA_DATABASECHANGELOGLOCK (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DBCHGLOGLOCK PRIMARY KEY (ID))

in db2 As400 does not have the type boolean.

To fix it, the code "database.getClass().isAssignableFrom(DB2Database.class)" should be replaced with "database instanceof DB2Database" 
the result of instance DB2iDatabase by"database.getClass().isAssignableFrom(DB2Database.class)" => false .it should be true.

maybe it shoould also override in the class DB2iDatabase the method supportsBooleanDataType and return false.

**Comment by Ecofred** [comment]
db2fori (db2 AS/400) supports BOOLEAN from 7.5 on (new release)
`supportsBooleanDataType` could check the build-in types catalog (present at least since 7.1)
```
select type_name
from sysibm.sqltypeinfo 
where type_name = 'BOOLEAN';
```
empty -> `false`; 1 record -> `true`

@tiran1984: it may be an issue for liquibase/liquibase-db2? or does it belongs to the core liquibase?

I may try my first PR. an override `supportsBooleanDataType` did the job in the extension... but to bad the DB2 family do not have a standard build-in type catalog.

**Comment by molivasdat** [comment]
Hi @tiran1984 can you add your PR to the db2i extension?
https://github.com/liquibase/liquibase-db2i

**Comment by Ecofred** [comment]
okay, done. Review and feedback welcome.

**Comment by tiran1984** [comment]
For me look your commit fine.

**Comment by kataggart** [comment]
This looks like it was resolved in https://github.com/liquibase/liquibase-db2i/pull/61

Closing
