### ISSUE TITLE
Distribute CLI JAR with all dependencies

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase#2751]
Currently, the Liquibase CLI JAR does not ship Picocli and is not usable through standard dependency management as-is.
This can be worked around by letting clients adding the Picocli dependency themselves, but it puts on them the burden of bookkeeping the Picocli version.

Having a functional CLI JAR is useful for integrations such as https://www.jbang.dev/.

**Comment by landsman** [comment]
yes!

**Comment by filipelautert** [comment]
@fbiville would PR https://github.com/liquibase/liquibase/pull/5042 help on that?

**Comment by fbiville** [comment]
But then it works by replacing `liquibase-core` with `liquibase-cli`, so I guess I just need to update the JBang integration to do that instead.

**Comment by fbiville** [comment]
I guess I hallucinated, `liquibase-cli` is not available in Maven Central.

**Comment by calle2010** [comment]
> @fbiville would PR #5042 help on that?

PR #5042 added picocli as an optional dependency. This does not really help from my point of view: When I have liquibase-core as a dependency and I want to add picocli then in Maven I still have to provide a version number and must remember to keep this up to date when Liquibase versions are changing.

I don't see a good solution here other than offering a liquibase-cli artifact which has this dependency as non-optional.

The Maven documentation also sees submodules as the way to solve this situation:

"Optional dependencies are used when it's not possible (for whatever reason) to split a project into sub-modules. The idea is that some of the dependencies are only used for certain features in the project and will not be needed if that feature isn't used. Ideally, such a feature would be split into a sub-module that depends on the core functionality project. This new subproject would have only non-optional dependencies, since you'd need them all if you decided to use the subproject's functionality."
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html
