### ISSUE TITLE
LoadData with Dates Failed while Column Type is From Property

### ISSUE THREAD

**Issue by olgunkaya** [liquibase/liquibase#2803]
## Environment
Maven home: C:\development\apache-maven-3.8.5
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: C:\development\java\jdk-11.0.10.9
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
**Liquibase Version**:
4.6.1
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
spring boot
**Liquibase Extension(s) & Version**: 
NA
**Database Vendor & Version**:
Oracle
**Operating System Type & Version**:
windows 10

## Description
loadData with dates failing.
Specifically
if column property type is coming from a defined property in master.xml, than liquibase identifies the column as String. 
Spesifically, debugged till the preparedStatement generation and found that;
`ExecutablePreparedStatementBase.java.applyColumnParameter -> col.getValue() ` returns a value. Thus the below checks discarded and entity tried to be saved as a String.

This was pretty ok with H2 disk based DB but, when I switch to prod profile and test loading data, it failed. 

## Steps To Reproduce

List the steps to reproduce the behavior.
1. create properties in master.xml as below
```
    <property name="datetimeType" value="datetime(6)" dbms="mysql, mariadb"/>
    <property name="datetimeType" value="datetime" dbms="oracle, mssql, postgresql, h2"/>
```
2. create a table with these types used in columns. **(table creation succeed)**
```
<createTable....>
...
            <column name="created_time" type="${datetimeType}">
                <constraints nullable="true" />
            </column>
....
</createTable>
```

3
a. Try loading data with the type coming from these properties again. 
```
<loadData
...
            <column name="created_time" type="${datetimeType}"/>
...
</loadData>
```
b. If the loadData column type changed to "date" without any placeholder, than it worked as expected.
```
<loadData
...
            <column name="created_time" type="date"/>
...
</loadData>
```

## Actual Behavior
Exception from oracle with message "ORA-01843: not a valid month" thrown

## Expected/Desired Behavior
Sample/Initial value to be persisted on database and usable across the app. 

## Screenshots (if appropriate)
NA

## Additional Context
NA

Note 1: I checked the column type here https://docs.liquibase.com/concepts/changelogs/attributes/column.html and datetime is available there. Possibly the column type does not support placeholder for custom properties.

Note 2: Sample date entry used during the test is was 
`2022-04-05T10:20:20`

Note 3: 
https://docs.oracle.com/cd/B19306_01/server.102/b14237/initparams132.htm#REFRN10131
I could of change the NLS_TIMESTAMP_FORMAT and got it working too but then it's like hacking liquibase at all :)

**Comment by nvoxland** [comment]
Just having `type="date"` in the loadData column is what you want to have regardless of the database.

For loadData, that "type" attribute isn't "the specific database type" but more of a "what general type of value is in the CSV file so liquibase knows how to handle it". By saying type="date", we know we should parse the value as an ISO date and send it to the data in whatever way the database takes dates.

But when you'd put type="date(6)" we don't recognize that as a known parsing type and silently fall back to "must just treat it as a string" and so pass the ISO-formatted date to the database, which is not a format oracle is expecting and it fails.

We'll look at maybe adding at least a warning message when you have a type we don't understand there, but because people have all sorts of values they may be putting in there we have to be careful not to unexpectedly break people too.
