### ISSUE TITLE
beforeColumn is not working when column is the first one

### ISSUE THREAD

**Issue by baguilarq** [liquibase/liquibase#2861]
## Environment

**Liquibase Version**: 4.10.0

**Liquibase Integration & Version**: None

**Liquibase Extension(s) & Version**: None

**Database Vendor & Version**: MySQL 5.6.51 (MySQL Community Server (GPL)) (from official Docker image `mysql`)

**Operating System Type & Version**:  Manjaro 21.2.6 (Qonos)

## Description

Using `beforeColumn` when adding a column as the first one, add that column as last in a table.

## Steps To Reproduce

`clinic_id` is the first column in `contact_info` table. 

```xml
<databaseChangeLog ...>
    <changeSet author="baguilar" id="1">
        <addColumn tableName="contact_info">
            <column name="id" type="INT" beforeColumn="clinic_id">
                <constraints nullable="false"/>
            </column>
        </addColumn>
    </changeSet>
</databaseChangeLog>
```

## Actual Behavior
Column `id` is added as the last one.

![image](https://user-images.githubusercontent.com/34453981/169419021-35744448-a414-4888-98a4-ab515c3f5e25.png)

## Expected/Desired Behavior
Column `id` should be the first one.

**Comment by kataggart** [comment]
please note older version of mysql here; may not support functionality

**Comment by FBurguer** [comment]
same issue on MySQL 8.1 and Liquibase 4.11

**Comment by nvoxland** [comment]
Looking into this, the trouble is that mysql does not support being able to specify "BEFORE" clauses in add column. https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

I created #2943 which better throws a validation error on mysql if you use beforeColumn since we can't support it. But this particular feature is something we can't support due to database limitations.
