### ISSUE TITLE
Conditional index wrongly generated with CLI generate-changelog command

### ISSUE THREAD

**Issue by DimiF4W** [liquibase/liquibase#2953]
## Environment

**Liquibase Version**:
version 4.10.0 #2501 built at 2022-05-04 14:27+0000

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
PostgreSQL 11.15 on x86_64-apple-darwin21.3.0, compiled by Apple clang version 13.0.0 (clang-1300.0.29.30), 64-bit 

**Operating System Type & Version**:
Mac

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
Local

## Description

A condition index is wrongly converted when using:
```
liquibase --changelog-file=dbchangelog.xml generate-changelog
```

We created an index with following SQL:
```
CREATE UNIQUE INDEX db_tbl_uc01 ON s.abc (x, y, z) WHERE (b = TRUE);
```

This results in the following xml export:
```
 <createIndex indexName="db_tbl_uc01" schemaName="s" tableName="abc" unique="true">
            <column computed="true" name="(b = true)"/>
            <column computed="true" name="(b = true)"/>
            <column computed="true" name="(b = true)"/>
   </createIndex>
```

So the columns x, y, z are missing as columns

**Comment by kataggart** [comment]
thanks @DimiF4W  we are taking a look - if you have five min to spare would love your [input!](https://bit.ly/lbcommsurvey)

**Comment by ecarneiro01** [comment]
This issue happens in version 4.12 too.

**Comment by FBurguer** [comment]
I got the a similiar output

```
        <createIndex indexName="db_tbl_uc01" tableName="abc" unique="true">
            <column computed="true" name="(b = true)"/>
            <column computed="true" name="(b = true)"/>
            <column computed="true" name="(b = true)"/>
        </createIndex>

```

**Comment by filipelautert** [comment]
Hi @DimiF4W !
Thanks for the report. We found out that mainly Postgresql and MSSQL server support conditional indexes (a WHERE when creating the index), so we implemented a fix that makes sure that the columns are corrected exported instead of the where clause (:man_facepalming: ). 
I discussed with @nvoxland , and implementing the "where" condition would be too specific for those databases and it's  not supported by Liquibase, thus the where part it's being ignored - at least columns are ok now.

PR https://github.com/liquibase/liquibase/pull/3366  fix makes sure that Postgresql and MSSQL works correctly.
