### ISSUE TITLE
restore best-effort behavior of afterColumn

### ISSUE THREAD

**Issue by dbyron-sf** [liquibase/liquibase#3091]
## Environment

**Liquibase Version**: 4.13.0

**Liquibase Integration & Version**: gradle, spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: mysql, postgresql

**Operating System Type & Version**:

**Infrastructure Type/Provider**:

## Description

https://github.com/spinnaker/orca (migrations are [here](https://github.com/spinnaker/orca/tree/master/orca-sql/src/main/resources/db/changelog)) uses `afterColumn` in some of its migrations, and tests those migrations using both mysql and postgresql.  Before version 4.13.0, and specifically https://github.com/liquibase/liquibase/pull/2943, afterColumn worked with mysql, and did nothing with postgresql.  With 4.13.0, afterColumn still works with mysql, but throws a validation error with postgresql.  For example:
```
PgTopApplicationExecutionCleanupPollingNotificationAgentSpec > initializationError FAILED
    com.netflix.spinnaker.kork.sql.test.SqlTestUtil$DatabaseInitializationFailed: liquibase.exception.ValidationFailedException: Validation Failed:
         4 changes have validation failures
              addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
              addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
              addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
              addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
        at com.netflix.spinnaker.kork.sql.test.SqlTestUtil.initDatabase(SqlTestUtil.java:248)
        at com.netflix.spinnaker.kork.sql.test.SqlTestUtil.initTcPostgresDatabase(SqlTestUtil.java:97)
        at com.netflix.spinnaker.orca.sql.cleanup.PgTopApplicationExecutionCleanupPollingNotificationAgentSpec.getDatabase(TopApplicationExecutionCleanupPollingNotificationAgentSpec.groovy:161)

        Caused by:
        liquibase.exception.ValidationFailedException: Validation Failed:
             4 changes have validation failures
                  addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
                  addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
                  addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
                  addAfterColumn is not allowed on postgresql, db/changelog/20180510-add-legacy-id-fields.yml::add-legacy-id-fields::cthielen
            at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:307)
            at liquibase.Liquibase.lambda$update$1(Liquibase.java:228)
            at liquibase.Scope.lambda$child$0(Scope.java:180)
            at liquibase.Scope.child(Scope.java:189)
            at liquibase.Scope.child(Scope.java:179)
            at liquibase.Scope.child(Scope.java:158)
            at liquibase.Liquibase.runInScope(Liquibase.java:2400)
            at liquibase.Liquibase.update(Liquibase.java:208)
            at liquibase.Liquibase.update(Liquibase.java:194)
            at liquibase.Liquibase.update(Liquibase.java:190)
            at liquibase.Liquibase.update(Liquibase.java:182)
            at com.netflix.spinnaker.kork.sql.test.SqlTestUtil.initDatabase(SqlTestUtil.java:246)
            ... 2 more
```
One use of `afterColumn` is:
```
    - addColumn:
        tableName: orchestration_stages
        columns:
        - column:
            name: legacy_id
            type: varchar(500)
            afterColumn: id
```

## Expected/Desired Behavior

https://github.com/liquibase/liquibase/pull/2943 notes that this is the new behavior.  I'd love a way to go back to the old behavior, where addColumn works where supported, and is ignored where it's not.  There are some migrations where adding e.g.:
```
modifySql:
  dbms: "mysql"
  append:
    value: " after id"
```
works, but many where it doesn't.

**Comment by dbyron-sf** [comment]
Turns out that https://github.com/liquibase/liquibase/issues/3094#issuecomment-1194426594 is actually the heart of the matter:
> I'm mainly interested in my changelogs not breaking, and your change breaks them both ways...
Leaving the postition="x" in breaks things, removing the attribute also breaks things, since the signature of the changeset changes.
>
> And yes, there is also the thing about different platforms, which is one of the main selling points for Liquibase :)

So even if it's possible to do things with custom sql, the changeset checksums fail.

I think what I'm really asking for is to change this from an enhancement to a bug.

**Comment by kataggart** [comment]
@dbyron-sf check out @nvoxland response on the related issue https://github.com/liquibase/liquibase/issues/3094#issuecomment-1195937172

It's funny because I was just finishing up doing the Liquibase University course on this very topic! So great timing. This post also might be helpful - https://www.liquibase.com/blog/what-affects-changeset-checksums

**Comment by dbyron-sf** [comment]
It's nice to learn that there are workarounds for this, and so the question of bug vs. feature isn't as clear as I thought.  Still though, I had a migration that used to work, and now doesn't, and the old behavior of doing what afterColumn does where supported, is much preferred.

**Comment by jfisbein** [comment]
I agree with @dbyron-sf, this is a breaking change (something that worked in the past, does not work in the new version).
This breaking change makes my DB migration not reproducible, I cannot execute the same files I executed in the past to create a new instance of the database.

I think this feature should be reverted or at least allow to be disabled in some way (feature-flag, parameter, configuration file, etc)

**Comment by nvoxland** [comment]
I'd like to expand this ticket to be a more broad "support best-effort in general" ticket.

Currently, the way Liquibase is set up is that it follows what the changelog says it should do. It you specify an object type to create or an attribute to set on an object, Liquibase makes sure those are done as you say or throws a validation error.

But while that's the usually-expected behavior, there is times people want the opposite. They want to be able to say `add afterColumn='x'` and are fine if it doesn't actually get added after column x. 

Other examples include:
- Database doesn't support sequences, so just don't create/drop/alter them
- AddColumn addAtPosition
- AddPrimaryKey clustered
- CreateIndex clustered
- CreateSequence ordered. minValue, maxValue,
- ... and many more...

I don't want to over-complicate the feature, but I also want to make sure it's useful so I'd like to get some feedback and discussion before someone spends a bunch of time implementing something.

**The big question I have off the bat is: _How fine-grained does the "ignore validation for X" have to be?_** 

Can it just be "don't do validation anymore"? That seems a bit too broad and dangerous....

But, if it's just on some some, who decides? The user specifying something like `validationIgnore=addColumn.addAtPosition,createSquence.ordered`? Or the user specifying something like `validation=lax` and the logic in each change type deciding "CreateSequence.ordered is ignored in 'lax' mode but incrementBy still thows an error"? 

_Other suggestions on how the configuration would go??_

**What will make this difficult to implement** is that the code in each SqlGenerator tends to be:
1. In the validate() function, throw an exception if a field is set which is not supported
2. In the generateSql() function, if a field is not null include something in the SQL for it

That means that if we simply ignore "database doesn't support 'order' in createSequence" in the validation step, that field will still be set when we get to generateSql() and the existing code will include "ORDERED" in the SQL assuming it must be OK. We'll have to update all the generateSql logic to know to ignore specified fields when the database doesn't support it. If someone has a great idea on how to avoid this all this work in how the configuration/functionality works, that would be great :)

**Comment by nvoxland** [comment]
Until the enhancement gets released, beyond the options of:
- Remove the problem attributes completely
- Use modifySql with dbms attribute
- Create two changesSets, one with `dbms="h2"` and one with `dbms="!h2"` or whatever is correct for your setup

you can also create extensions in Java that allow you to run whatever logic you may want. 

A class like this:
```java
import liquibase.database.Database;
import liquibase.database.core.H2Database;
import liquibase.exception.ValidationErrors;
import liquibase.sqlgenerator.SqlGeneratorChain;
import liquibase.statement.core.AddColumnStatement;

public class MyAddColumnGenerator extends AddColumnGenerator {

    @Override
    public int getPriority() {
        return super.getPriority() + 10;
    }

    @Override
    public ValidationErrors validate(AddColumnStatement statement, Database database, SqlGeneratorChain sqlGeneratorChain) {
        if (!(database instanceof H2Database)) {
            statement.setAddAfterColumn(null);
        }
        return super.validate(statement, database, sqlGeneratorChain);
    }
}
```

will make it so `addAfterColumn` gets cleared out if the database is not an h2 database.

It's a quick hack, but if this is causing a lot of problems for you it may be a good workaround for you.

Remember: You do have to register it by creating a `META-INF/services/liquibase.sqlgenerator.SqlGenerator` file containing the name of your class in the jar file with your compiled class, then include that jar in the classpath of whatever is running Liquibase.

**Comment by dbyron-sf** [comment]
> The big question I have off the bat is: _How fine-grained does the "ignore validation for X" have to be?_

Does "best effort" / "ignore this if it's unsupported" necessarily mean the same thing as "ignore validation" ?  My initial thought is that I don't really want to have to know the details of what each DBMS supports and doesn't, but I suspect there are limits to this, and discussing them will likely expose lots of my ignorance about liquibase and databases :)

Like, if the configuration was broad enough to only say "ignoreUnsupported=true", and I specify a column to add, is there some scenario where the column doesn't get added at all?  I would want that to fail.

**Comment by nvoxland** [comment]
#3537 had some similar discussion on this issue.

A suggestion there is to use the existing `strict` flag to control whether to count some of these as validations as optional. That is still the "no controllable granularity, the code knows what settings are 'flexible' and allows them be skipped" setting, just using the existing flag.

**Comment by dbyron-sf** [comment]
Is https://docs.liquibase.com/concepts/connections/creating-config-properties.html the right place to learn about what `strict` means today?
```
strict=<true\|false> | Specifies whether Liquibase fails with a validation error when the properties file, liquibase.properties, contains unknown or inapplicable properties. Default value is false.
```
If this is right, we might be overloading it too much to do this as well.  But a similar new flag where the code knows the flexible settings seems like a good approach.

**Comment by nvoxland** [comment]
That is probably the best description. It is really just used currently when checking the liquibase.properties file and environment variables to fail if there are settings in them that do not correspond to valid settings for the command you are running. The problem with that flag, is the default is "false" which is opposite of what we want this setting to be as a default.

There is also `liquibase.changelogParseMode = [strict | lax]` which is probably the better candidate for a reused field. That is currently used to decide what to do if there is a change or precondition in your changelog which isn't known by liquibase. The default there is "strict" which is good. But is it better to have more flags or less flags? More flags give you more granular control, but less flags give you easier documentation. When we made the `changelogParseMode`  we purposefully left it as a string not a boolean, so we have options around what the value is. We could do something like `liquibase.changelogParseMode=!validateDatabaseSupport,!oldXsd` or something to mean "strict except lax on those two things".

But I think before getting into whether to reuse a field or not, we need to figure out the desired functionality. The config options will probably fall naturally out of that.

---

> My initial thought is that I don't really want to have to know the details of what each DBMS supports and doesn't [...] If the configuration was broad enough to only say "ignoreUnsupported=true", and I specify a column to add, is there some scenario where the column doesn't get added at all? I would want that to fail.

That is really the rub. In the general case, people don't want to have to care about what each database supports -- until they do. Like you didn't care that `afterColumn` didn't work on postgresql but #2861 was logged because `beforeColumn` was ignored on mysql. And like you say, if you have something like `addColumn` and you try to run it against a mongodb database which doesn't support that you probably don't want it to silently fail?

That's where I come down on the side of "Liquibase should be strict on doing what you tell it to do, but give you options to handle that strictness". I think that for "most" people, they do want to care about the database differences because it will end up impacting them. 

For example, if you are making an application that runs on both mysql and postgresql, if the care enough about the ordering of columns to feel like they need to use `beforeColumn` or `afterColumn` it is important that they know it's not supported on one or the other database. Knowing that, they will likely want to remove that attribute in order to keep their schemas as similar as possible between the database types. Similarly, if someone is using mysql and explicitly asks for `beforeColumn` and don't know that it's not something mysql itself supports, it is surprising to them when we just don't respect it. They want to learn that mysql doesn't support that so they need to either not care about the order or find a different way to get what they want.

There is a class of people who are OK with those differences after learning that there will be differences, which is why we need ways to let them keep those differences. But I think that workflow is:
1. User runs update and gets a "x is not supported on your database" error
2. User decides what to do about it. Is it a one-off thing that they want to say "for this changeset, make X not apply database Y"? Or now that they know that, do they want to say "for all changesets, I'm fine with not applying X to database Y"?

But regardless of what they pick, I think it's always in relation to specific flag X.  I don't think there's really anyone who will want to say "In general, liquibase should just skip over stuff I tell it to do but the database happens to not support". They explicitly said they wanted things for a reason.

So I'm feeling like the functionality should be around specifically whitelisting change attributes that are OK to ignore for database that do not support them.

Does that make sense?

**Comment by dbyron-sf** [comment]
Thanks for getting the details down here.  I totally agree that this workflow makes sense.

**Comment by nvoxland** [comment]
Thinking on implementation a bit, I'm thinking that a `<modifyChange>`  tag may be the best approach?

- It's consistent in spirit with the existing `<modifySql>` 
- Having it in the changelog keeps that "we expect the 'ignore' logic to be part of the changelog code vs. a runtime configuration thing which could be forgotten and/or be different than what the changelog authors expected
- It is more verbose/structured than we can get in a runtime configuration
- We can have it supported at both the root changelog level where it applies to everything or within specific changesets

Examples:

```
        <modifyChange change="addColumn" dbms="postgresql">
            <remove name="afterColumn"/>
        </modifyChange>
```
or
```
        <modifyChange change="addColumn" contextFilter="qa">
            <replace name="type" replace="varchar(20)" with="varchar(50)"  />
        </modifyChange>
```
which can be in either the root of changelog or in particular changesets.

If it's in the root, it acts like preconditions and gets "hoisted" across all the include'd changesets, not just to the particular changelog it's in.

Then, as part of the ChangeSet execution process, it would modify the changes in the changesets accordingly **before** validation happens.

I think this will keep the implementation simplest, because the actual change logic doesn't change -- it still **_always_** validates strictly, it's just that now the validation will pass. So the changes should be pretty isolated.

Seem like a good plan?

One issue will be that I know the internal team is busy on other projects for a bit, so it's likely to not make the top of their priority list for a while. Is anyone interested in implementing it? I can certainly help with pointers if you are.

**Comment by dbyron-sf** [comment]
This seems reasonable.  I think my only potential quibble is with the `dbms="postgresql"` bit.  It follows from the workflow outlined above, where someone runs an update on postgres and learns afterColumn isn't supported....so then they add modifySql to remove it, and the detail of postgresql is nicely specific....My mind is wandering to a place where postgres supports afterColumn one day...but that's probably unlikely.

As for making the code changes...it's possible I know of some folks who may have time...no promises...but please share pointers if you've got some.

**Comment by nvoxland** [comment]
> My mind is wandering to a place where postgres supports afterColumn one day...but that's probably unlikely.

We have the same question on the "dbms" tag in general and figure we can support a syntax like `dbms=postgresql:14` but nobody has asked for yet yet, so must be unlikely.

I always have pointers :) 

But, in case it gets to be a bit until someone looks at it, I'll wait to offer them until someone thinks they'll have a chance to look. If you find anyone interested in helping they can drop a line here.

**Comment by kirangodishala** [comment]
@nvoxland @dbyron-sf - I am willing to work on this change. Is there any developer guide sort of documentation to start with?

**Comment by kirangodishala** [comment]
@nvoxland - initially I thought of going with creating a new interface(say ChangeVisitor) similar to SqlVisitor to apply modifyChange but then I though the complete logic can be implemented under `case "modifyChange" ` in handleChildNode() of ChangeSet. Could you suggest if my approach sounds right?

**Comment by kirangodishala** [comment]
Thanks for the response @nvoxland. I took off on Friday. Will try to implement the changes as suggested above and add comments here if I need any more inputs.

**Comment by kirangodishala** [comment]
> If it's in the root, it acts like preconditions and gets "hoisted" across all the include'd changesets, not just to the particular changelog it's in.

@nvoxland - you mean "not just to the particular `changeset` it's in" ? So if we have multiple changelogs with `afterColumn` we need to add `modifyChange` in each of them. Instead can we have it in the master changelog file so that all the included changelogs can take advantage of it?

**Comment by kirangodishala** [comment]
@nvoxland - created PR - https://github.com/liquibase/liquibase/pull/3978
I took a design decision to apply the `ChangeVisitor` while loading the change itself. Please review and provide feedback.

**Comment by nvoxland** [comment]
Thanks, @kirangodishala! I'll take a look

**Comment by szape89** [comment]
> > If it's in the root, it acts like preconditions and gets "hoisted" across all the include'd changesets, not just to the particular changelog it's in.
> 
> @nvoxland - you mean "not just to the particular `changeset` it's in" ? So if we have multiple changelogs with `afterColumn` we need to add `modifyChange` in each of them. Instead can we have it in the master changelog file so that all the included changelogs can take advantage of it?

This was not answered, but I'm looking for something similar what @nvoxland mentioned, but probably in a bit different scenario.

In case of XML format I can only get it working if inside `databaseChangeLog` the `removeChangeSetProperty` is followed by multiple `changeSet` but not with multiple `include` or a single `includeAll`.

@kirangodishala Should I expect these includes to work or this has not been implemented?
