### ISSUE TITLE
md5sum column being update to NULL when I try to migrate from 3.5.3 to 4.8.0 or 4.9.0

### ISSUE THREAD

**Issue by nvkvc** [liquibase/liquibase#3109]
So, exactly as I wrote in the title, I am trying to update my Java application to use newer version of liquibase-core library as there are vulnerabilities found in the lower versions. However, when I do upgrade my liquibase-core library and when I start migration with `Liquibase#update(Contexts contexts, LabelExpression labelExpression)` method, I see column md5sum in databasechangelog table being set to NULL, instead of being recalculated to someting like `8:92a9dbde7a04a1d2ee1aec16beaf0d6b`.
Underlying database is postgresql. Did anyone experienced someting similar? Just to mention that I am getting no errors or exceptions, it's just md5sum column being overridden to NULL for all 3.5.3 migrations. New migrations are getting correct md5sum value, as expected.

**Comment by kataggart** [comment]
@nvkvc do all the changesets that are now NULL on databasechangelog still exist in the changelog file? Thanks

**Comment by nvkvc** [comment]
> @nvkvc do all the changesets that are now NULL on databasechangelog still exist in the changelog file? Thanks

@kataggart Yes, they do exists, changelog files are still there. The only thing I updated in changelog files is that I have added logicalFilePath attribute to keep it backward compatible. Thanks

**Comment by nvkvc** [comment]
There is a workaround for this issue:
First bump 3.5.3 version to 3.6.X version (as in this version are introduced some breaking changes reg. checksum logic)
After liquibase version is bumped to 3.6.X version, check your newly updated md5sum column (it should contain values something like 8:92a9dbde7a04a1d2ee1aec16beaf0d6b, comparing to previous 7:62a9cefa5a04a1d2ee1aec16beaf0d6b).
After that you can safely bump to 4.8 version

FYI @kataggart

**Comment by kataggart** [comment]
Thanks @nvkvc for the research and workaround!

**Comment by filipelautert** [comment]
Hello @nvkvc 
I'm trying to reproduce this issue but I'm not able to.  I'm following those steps (all from the command line):
*using liquibase 3.5.3, run a simple changelog on postgresql 14 that generates md5 7:63ad9afb467364dc6ed8bc56bc241c65 
* run again the update but using liquibase 4.8.0 or latest , and then md5sum gets update to 8:ddd8f0858f59a9b98e85ef6ffe800e82

I tried adding the logicalFilePath to see it fails, but still doing ok. I'm not sure if it may be ok for me because I"m using just a few changesets, but this should not impact it.

So, did you try using clearChecksums command before running the update when migrating? Also, do you thing you can try to reproduce it with liquibase 4.17 (see we had some more fixes changelogs lately)? 

Otherwise I see that you are using liquibase within your code as a java library - would it be reproducible using the command line version?

Thanks

**Comment by filipelautert** [comment]
Hello, as this seems to be fixed on 4.17 I'll close this issue. But if it still happening please reopen it.
