### ISSUE TITLE
'execute-sql' command return results in alphabetical order and not as specified in the given query

### ISSUE THREAD

**Issue by yevon** [liquibase/liquibase#3351]
**Liquibase Version**:
4.16.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Database Vendor & Version**:
Postgresql 14

**Operating System Type & Version**:
Ubuntu 22.04

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
On premise

## Description
Liquibase execute-sql + --sql + --output-file seems to no respect columns order as specified by the query when trying to save the output as CSV.

## Steps To Reproduce

Execute a query like this one:

`liquibase execute-sql --output-file=validation-results.csv --sql "select schema, name, existstable, existsapi, mustcreateapi, hasindexes, hasrules, hastriggers, hasrowsecurity, tablefilename, apiviewfilename, tablefileheader, apiviewfileheader from app.verify_model_v order by schema, name"`

This results in a csv file in this order:

```
Output of select schema, name, existstable, existsapi, mustcreateapi, hasindexes, hasrules, hastriggers, hasrowsecurity, tablefilename, apiviewfilename, tablefileheader, apiviewfileheader from app.verify_model_v order by schema, name:
APIVIEWFILEHEADER | APIVIEWFILENAME | EXISTSAPI | EXISTSTABLE | HASINDEXES | HASROWSECURITY | HASRULES | HASTRIGGERS | MUSTCREATEAPI | NAME | SCHEMA | TABLEFILEHEADER | TABLEFILENAME |
```

Which does not match query order.

## Actual Behavior
Column order is wrong.

## Expected/Desired Behavior
Respect column order as specified by the query by default.

**Comment by yevon** [comment]
It doesn't even preserve rows order.

**Comment by MalloD12** [comment]
Hi @yevon,

Thank you for raising this issue for us. I was trying to reproduce it but couldn't get the same behavior as you did. Executed below command: 

```
liquibase execute-sql --output-file=validation-results.csv --sql "select lastname, col1, col2, col3, id, firstname, col4 from person order by firstname, col2
```

and got this result:

```
Output of select lastname, col1, col2, col3, id, firstname, col4 from person order by firstname, col2:
-- Empty Resultset --
```

I tried some other combinations as well and got the expected result for each of them. Could you please try again with the latest version?

In the meantime, I'll create a ticket for our docs team, so they can update this docs page [Liquibase execute-sql docs](https://docs.liquibase.com/commands/execute-sql.html).

Thanks,
Daniel.

**Comment by jglass524** [comment]
I can reproduce this issue running liquibase 4.23.1 on ubuntu 22.04. liquibase is always returning the columns in alphabetical order. you can therefore change the order of the columns using an "as" clause.

----- example 1 -----

# notice that in the output, the B_CURRENT_SCHEMA column comes after A_NOW even though current_schema() was specified before now() in the select statement
liquibase execute-sql --username lcm2 --password lcm2 --url jdbc:postgresql://localhost:5432/lcm2 --sql "select current_schema() as b_current_schema, now() as a_now"
Output of select current_schema() as b_current_schema, now() as a_now:
A_NOW | B_CURRENT_SCHEMA |
2023-08-21 14:30:50.564451 | public | 

----- example 2 -----

# changing the "as" clauses so that the current_schema() column comes first
liquibase execute-sql --username lcm2 --password lcm2 --url jdbc:postgresql://localhost:5432/lcm2 --sql "select current_schema() as a_current_schema, now() as b_now"
Output of select current_schema() as a_current_schema, now() as b_now:
A_CURRENT_SCHEMA | B_NOW |
public | 2023-08-21 14:32:28.62136 |

**Comment by kevin-atx** [comment]
@MalloD12 - could you look in the code and see where the software is forcing the output to be alphabetical vs. just leaving it how it's returned from the query? Would changing the behavior impact anything else, or is it isolated to the execute-sql command?

**Comment by MalloD12** [comment]
Hi Kevin, this is isolated to `execute-sql` and columns are displayed sorted because we were using a SortedSet collection. I have created a [PR](https://github.com/liquibase/liquibase/pull/4994) and linked a PD ticket there to update docs.

Thanks,
Daniel.
