### ISSUE TITLE
liquibase against hive db fails trying to delete databasechangeloglock

### ISSUE THREAD

**Issue by neesha-panigrahi** [liquibase/liquibase#3424]
[HiveDeleteException.txt] (https://github.com/liquibase/liquibase/files/9887209/HiveDeleteException.txt)
[Liquibaselogs.txt] (https://github.com/liquibase/liquibase/files/9887213/Liquibaselogs.txt)

**Comment by nvoxland** [comment]
Liquibase shouldn't be attempting to delete from the databasechangeloglock table, and the exception is really that Liquibase always expects there to be one row to update but that record is gone.

We don't have any special support for Hive in core Liquibase, and we don't have an extension we maintain to add support for it. But we do try in liquibase core to use standard SQL for unknown database types so we sometimes don't need special support for a database and/or you are maybe using an extension from somebody else. 

Can you tell me a bit more on how you have your liquibase env set up? That can help us know if it's an issue with an extension deleting from the table instead of updating the table, or if the generic "set up the databaeschangeloglock" logic created the table but never inserted into it correctly? Or if you had to create the databasechangeloglock able manually and just created it without inserting into it too?

**Comment by neesha-panigrahi** [comment]
yes, have created the databasechangeloglock manually because initally i was getting error as  (DATETIME type isn’t supported yet. Please use DATE or TIMESTAMP instead), (https://github.com/liquibase/liquibase/issues/3409),

CREATE TABLE default.DATABASECHANGELOGLOCK(
  id int not null,
  LOCKED BOOLEAN not null,
  LOCKGRANTED timestamp,
  LOCKEDBY string,
CONSTRAINT PK_DATABASECHANGELOGLOCK
PRIMARY KEY (ID) disable novalidate)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES (
  'field.delim'=',',
  'serialization.format'=',')
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'hdfs://cdp1.profinch.com:8020/warehouse/tablespace/managed/hive/DATABASECHANGELOGLOCK'
TBLPROPERTIES (
  'bucketing_version'='2',
  'transactional'='true',
  'transactional_properties'='insert_only',
  'transient_lastDdlTime'='1664356503');





CREATE TABLE default.databasechangelog(
      id string NOT NULL,
    author string NOT NULL,
    filename string NOT NULL,
    dateexecuted timestamp NOT NULL,
    orderexecuted int NOT NULL,
    exectype string NOT NULL,
    md5sum string,
    description string,
    comments string,
    tag string,
    liquibase string,
    contexts string,
    labels string,
    deployment_id string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES (
  'field.delim'=',',
  'serialization.format'=',')
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'hdfs://cdp1.profinch.com:8020/warehouse/tablespace/managed/hive/DATABASECHANGELOG'
TBLPROPERTIES (
  'bucketing_version'='2',
  'transactional'='true',
  'transactional_properties'='insert_only',
  'transient_lastDdlTime'='1664356503');
  
INSERT INTO default.DATABASECHANGELOGLOCK (ID, locked, lockgranted, lockedby) VALUES (1, 0, NULL, NULL);



have downloaded liquibase version- 4.14.0 and  hive jdbc jar from cloudera.

**Comment by neesha-panigrahi** [comment]
haven't heard any resolution for the above bug since long time.

**Comment by neesha-panigrahi** [comment]
hi, haven' t reaceived any solution for the above bug, can anyone help me on that?

**Comment by nvoxland** [comment]
Liquibase doesn't currently support or recognize hive natively. I see there is https://github.com/asm0dey/liquibase-hive or https://github.com/eselyavka/liquibase-impala or maybe a few other extensions that add support for hive via an extension. Using one of those may help?

**Comment by kevin-atx** [comment]
Per @nvoxland , please try one of the two community extensions listed in the previous comment to see if that helps. Closing this ticket.
