### ISSUE TITLE
Incorrect SQL generated for SQLite dropColumn, preventing the column from being dropped.

### ISSUE THREAD

**Issue by XDelphiGrl** [liquibase/liquibase#3459]
## Environment 

**Liquibase Version**: 4.17.2

**Liquibase Integration & Version** CLI

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: SQLite, 3.36.0

**Operating System Type & Version**: N/A

**Infrastructure Type/Provider**: Docker container

## Description

The dropColumn changeset for SQLLite does not actually cause a column to be dropped. It makes a temporary table, drops the temporary table and does nothing with the column you expect to drop.

This doesn’t drop any column and overall behavior doesn’t look right.
## Steps To Reproduce
Run updateSql command against sqlite database with this changelog

```
<changeSet id="1" author="as">
        <createTable tableName="test_table">
            <column name="test_id" type="int">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="test_column" type="varchar(50)">
                <constraints nullable="false"/>
            </column>
        </createTable>
    </changeSet>
    <changeSet id="2" author="as">
        <dropColumn tableName="test_table" columnName="test_column"/>
    </changeSet>
```

## Actual Behavior
Generated sql does not drop the column. This is the generated SQL:
```
CREATE TABLE test_table (test_id INTEGER NOT NULL, test_column VARCHAR(50) NOT NULL, CONSTRAINT PK_TEST_TABLE PRIMARY KEY (test_id))
ALTER TABLE test_table RENAME TO test_table_temporary
CREATE TABLE test_table ()
DROP TABLE test_table_temporary
REINDEX test_table
```

## Expected/Desired Behavior
Generated SQL has a DROP COLUMN

## Screenshots (if appropriate)
N/A

## Additional Context
N/A

**Comment by StevenMassaro** [comment]
This is a confusing situation that I don’t think has a simple fix.

Here’s the details:

SQLite does not support drop column statements. In order to drop a column with SQLite, you must rename your existing table, create a new table without the undesired column, copy the data from the existing to the new, then drop the existing. That is what Liquibase is attempting to do with the generated SQL script that is shown in the description of this ticket.

The problem comes from the fact that the user is attempting to deploy both the table creation and drop column changes in one deployment. When generating the SQL for a drop column change, Liquibase queries the database to find the columns that need to be duplicated in the replacement table. Since the table has not been created yet (because that change hasn’t been deployed yet), Liquibase finds no table and doesn’t know what columns to include in the new table.

If they were deployed separately, Liquibase would not have this problem (see code below).

We're going to "fix" this by updating the documentation for the dropColumn change type to clarify this behavior.

```
PS C:\dev\temp\DAT-12321> liquibase updatesql
Starting Liquibase at 13:09:40 (version [local build] #0 built at 2023-04-10 15:34+0000)
Liquibase Version: [local build]
Liquibase Labs [local build] by Liquibase licensed to Dev until Sat Dec 30 22:59:59 CST 2023
-- Lock Database
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'LAPTOP-EUMGOM2R (172.22.160.1)', LOCKGRANTED = CURRENT_TIMESTAMP WHERE ID = 1 AND LOCKED = 0;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: example-changelog.xml
-- Ran at: 4/10/23, 1:09 PM
-- Against: null@jdbc:sqlite:example.db
-- Liquibase version: [local build]
-- *********************************************************************

-- Changeset example-changelog.xml::2::as
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
ALTER TABLE test_table RENAME TO test_table_temporary;

CREATE TABLE test_table (test_id INTEGER NOT NULL, test_column VARCHAR(50) NOT NULL, CONSTRAINT PK_TEST_TABLE PRIMARY KEY (test_id));

INSERT INTO test_table (test_id,test_column) SELECT test_id,test_column FROM test_table_temporary;

DROP TABLE test_table_temporary;

REINDEX test_table;

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2', 'as', 'example-changelog.xml', CURRENT_TIMESTAMP, 2, '8:60e5b425d55555c784e55d6ac73f4e31', 'dropColumn columnName=test_column, tableName=test_table', '', 'EXECUTED', NULL, NULL, 'DEV', '1150180575');

-- Release Database Lock
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

Liquibase command 'updateSql' was executed successfully.
```
