### ISSUE TITLE
[BUG]  liquibase.resource.FileSystemResourceAccessor removed in 4.17.0

### ISSUE THREAD

**Issue by farmboy0** [liquibase/liquibase#3478]
## Environment

**Liquibase Version**: 4.17.0

**Liquibase Integration & Version**: CLI 4.17.0

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: 

**Operating System Type & Version**:

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

The class liquibase.resource.FileSystemResourceAccessor is absent from the 4.17.0 release,
it was still in the 4.16.0 release but no major version increase has occured.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

Please add the class back.

**Comment by FBurguer** [comment]
Hi! [Here ](https://github.com/liquibase/liquibase/issues/3064) are the changes made, it was an intended change. Maybe looking at this changes may help you with your problem!

**Comment by farmboy0** [comment]
If this was an intented breaking change then why wasn't the major version increased?

**Comment by FBurguer** [comment]
I do not know. I will bring this up to the team. This may fix the break though https://github.com/liquibase/liquibase/pull/3064#issuecomment-1278983000

**Comment by nvoxland** [comment]
@farmboy0 the reason we didn't increment the major version is because we're in the middle of a series of mid-sized refactorings. We're trying to continue to preserve API compatibility as we make them, but they are large enough that it's not always completely possible for all uses. But at the same time, we don't want to be incrementing the major version every 3 months when ideally it's normally not a breaking change for most people. So trying to find a bit of a balance there.

The short answer is what's in the above comment: FileSystemResourceAccessor got replaced by DirectoryResourceAccessor and/or ZipResourceAccessor. We kept compatibility for people using pre-created ResourceAccessors but constructing and extending FileSystemResourceAccessor was complex enough to map the new, better defined behavior over that we worried that having a clean "class not found" break will be easier for people to fix than subtle behavior changes.

But, also looking for feedback on how you are using FileSystemResourceAccessor and what makes it difficult to make the shift. We can always look at bringing back a deprecated version of the file if it turns out that is needed.

**Comment by farmboy0** [comment]
Its not needed to bring the class back, I was able to simply remove its usage altogether. I just didn't expect any need to do anything at all as I only updated to a new minor version.

**Comment by nvoxland** [comment]
Glad you were able to get it fixed, thanks. 

And yeah, that's a good expectation to not have to do anything with a minor version. We're trying hard to avoid still, but have the rules slightly relaxed for the time being before going back to the old "strong semver" requirements.

**Comment by amy-b-cheng** [comment]
@nvoxland I just ran into this on upgrading my liquibase version to 4.17.2. I was previously constructing a  FileSystemResourceAccessor(/path/to/changelog.xml, /path/to/folder/holding/changesets/). Do I now have to create a CompositeResourceAccessor with 2 DirectoryResourceAccessors, one for my changelog.xml file and one for the folder containing changesets?

**Comment by farmboy0** [comment]
An even better way would have been to bundle all the breaking changes and then release one major version upgrade with all of them in it.

**Comment by farmboy0** [comment]
AFAIU the class was removed because it was deemed to complicated to be adopted to the breakage. So avoiding it wasnt possible.

**Comment by nvoxland** [comment]
> @nvoxland I just ran into this on upgrading my liquibase version to 4.17.2. I was previously constructing a FileSystemResourceAccessor(/path/to/changelog.xml, /path/to/folder/holding/changesets/). Do I now have to create a CompositeResourceAccessor with 2 DirectoryResourceAccessors, one for my changelog.xml file and one for the folder containing changesets?

Yes, that's what you'd want to do, @amy-b-cheng

**Comment by nvoxland** [comment]
> An even better way would have been to bundle all the breaking changes and then release one major version upgrade with all of them in it.

> But my point is that breakage should be avoided even then in favour of deprecation and letting the ecosystem adapt slowly. If 4.17 was named 5 and there would have never been any other 4.x releases, then for the ecosystem, the major/minor distinction wouldn't matter all that much.


> AFAIU the class was removed because it was deemed to complicated to be adopted to the breakage. So avoiding it wasnt possible.

I agree with all these points :) 

`breakage should be avoided even then in favour of deprecation and letting the ecosystem adapt slowly` is our overall policy. I had tried the `bundle all the breaking changes and then release one major version upgrade with all of them in it` approach, but kept hitting the fact that "all the breaking changes" gets to be a lot both to implement and also for users to consume. 

As the branch were we were working on collecting all those changes started to diverge, it got more and more difficult to balance work across both the branches and both suffered. And we could see how having that large jump would be hard for users because there would be so much changing at a time. We definitely don't want to hit the h2 pattern and that is where that route was starting to look. 

So we have taking the `make changes, deprecate the old versions, then remove them over time` approach. But depending on the change that can be harder or easier to do. And it's also hard to tell how actually-used various classes are. For classes that are obviously often used we try very hard to keep compatibility. For ones that seem less commonly used, we still try but also have a point where we say "it's not worth the effort to keep this compatible, instead lets talk migration path". 

It sounds like FileSystemResourceAccessor is one that's used more often than we were expecting it to have been so probably worth taking a 2nd look at whether it can be brought back as a deprecated version. 

I can't make a PR and test it out just now, but I attached a patch file with what might work out.

That should allow people to still construct new FileSystemResourceAccessors like before and the base ResourceAccessor interface has `default` methods for to provide the old, compatible methods on there. 

It is still different than before in that it now extends AbstractResourceAccessor so even though I kept the `addRootPath()` methods for compatiblity, there are protected methods which are now gone so still not completely compatible for people writing subclasses of FileResourceAccessor. But perhaps this is a good intermediate step between "class is gone" and "100% compatible"?
[Restore_FileSystemResourceAccessor.zip](https://github.com/liquibase/liquibase/files/10070476/Restore_FileSystemResourceAccessor.zip)

**Comment by nvoxland** [comment]
I am shifting my role to be less focused on helping implement the changes to liquibase and more working with everyone building around and in Liquibase. I've not had enough time to keep up with how all the projects end up using liquibase in order to get more than gut-level guesses on things like "what APIs are people using?" and am looking forward to having the time to better work with all of you more consistently and proactively.

**Comment by filipelautert** [comment]
Hey @nvoxland - as discussed let's try to release this fix with Liquibase 4.18 , so people using it can skip 4.17 . thanks for the "patch"!
