### ISSUE TITLE
Error after the version upgrade is too absolute, can it be more friendly? such as validate beforeColumn/afterColumn in the AddColumnGenerator.

### ISSUE THREAD

**Issue by Yogurt-lei** [liquibase/liquibase#3537]
## Environment

**Liquibase Version**: 4.17.2

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: Hana, postgreSQL also 4.17.2

## Description

In this validate method, you can see we strict to validate when datasource is not MySQL and H2 , it will throw error that the field is not support

https://github.com/liquibase/liquibase/blob/347c33d055305df45b5df8ba70f0ed03cdb1ce20/liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java#L53-L84

## Steps To Reproduce

When use Hana or postgreSQL, and use the unsupported field like 
``` xml
<addColumn tableName="test_table">
          <column name="a_field_to_add" type="VARCHAR(5)" beforeColumn="code"/>
 </addColumn>
```
As you know, beforeColumn/AfterColumn is a strict validation in the version 4.17.2

## Actual Behavior
Will throw exception like **beforeColumn / afterColumn is not support in hana**

## Expected/Desired Behavior
We can let it more configurable, instead of just throwing an error

## Screenshots (if appropriate)

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/22915313/205861750-5caa3155-8076-4dc3-bb75-d23da19fde75.png">

## Additional Context

As i metioned, can we let it configurable?

**Comment by FBurguer** [comment]
Hello! At this moment we dont support this feature and at this moment we dont intent to. The reason is that setting a configuation to ignore certain parts of a changeset on the validation can be tricky and generate more problems that it solves. We are open to have a conversation about with the community to see if this feature is found useful by part of the community. 
However, for the case, there is a nice workaround. On this specific example changeset 
```
<addColumn tableName="test_table">
          <column name="a_field_to_add" type="VARCHAR(5)" beforeColumn="code"/>
 </addColumn>
```
We can do database specific `modifySQL` so the `beforeColumn` only apllies to databases of your choice, example:
```
<addColumn tableName="test_table">
   <column name="a_field_to_ad" type=""VARCHAR(5)"/>
</addColumn>
<modifySql>
   <append> before column code</append>
</modifySql>
```
this changeset does a `create table test_table(a_field_to_ad VARCHAR(5))` for all databases except Hana and for hana does the same but before the column code.

**Comment by nvoxland** [comment]
In your sample, @FBurguer you left out the `dbms="mysql"` or whatever attribute on `<modifySql>` which makes it targetted.

**Comment by nvoxland** [comment]
The overall problem of "when do we silently ignore validation errors vs when do we throw them" is a good one to come up with a better solution for. 

Our current approach is "if the user specifies they want something something, like `beforeColumn` and we can't deliver that, we should throw a validation error". It's not always consistent on that because historically we tried to be flexible and just silently ignore it if it seemed "obvious" that the database is just not going to support it. 

But in practice, that ends up feeling random and inconsistent and so we're trying to move to being more consistent on "we always do exactly what we're told to do". That seems the most straightforward and understandable. 

But, there are valid times when you want to specify something that works for some databases you support and is just ignored for others you don't. Like you want to control the column order if you can, and don't really care if you can't. But how do we do that?

We don't want a generic "ignore all validation" flag because that gets too broad.

Is it useful to have a flag to list which specific attributes we ignore? Like `ignore=beforeColumn`, or does that get too broad too? Especially since some attribute names get reused across tags and `ignore=type` is going to be too broad? 

Something like a new <modifyChange> tag good? So you can do:
```
<addColumn tableName="test_table">
          <column name="a_field_to_add" type="VARCHAR(5)" beforeColumn="code"/>
 </addColumn>
 <modifyChange dbms="!mysql">
    <removeAttribute name="beforeColumn"/>
 </modifyChange>
 ```?
 
 Or does that not seem as useful?
 
 What does people think? Anyone interested in trying to implement something around that?

**Comment by Yogurt-lei** [comment]
If we don't consider to compatible , maybe currently throw validation errors is a good way.
In my sample i drop the field tag like beforeColumn and afterColumn, and need to update md5sum manually, but if HANA support this feature in the future, user maybe need to rework for add it. so maybe we can set it as a warning message to inform user that this field tag is don't support currently.  than user update liquibase dependency lib easily in the future once target db support this feature.

Expect more conversation about this issue.

**Comment by nvoxland** [comment]
I'm going to close this in favor of #3091 to centralize discussion
