### ISSUE TITLE
Confusing documentation for `valueComputed ` in `update`

### ISSUE THREAD

**Issue by mjaggard** [liquibase/liquibase#3650]
## Description
The documentation on the `update` change type: https://docs.liquibase.com/change-types/update.html
contains information about `valueComputed` but states that "A value that is returned from a function or procedure call. This attribute should contain the function name to call." however it seems† that a function or procedure name is not required and this attribute can actually be used to simply set a computed value of any type such as "another_column" or "2 * another_column", etc.
Perhaps this varies from one DB to another but it would be good to have this functionality documented.

† I have not tested this myself yet, simply read this: https://dba-presents.com/liquibase/249-liquibase-update-data-based-on-another-column

## Snip
Since this is a documentation issue, I don't think the remaining questions in the bug report template are relevant.

**Comment by cmmay** [comment]
@adrian-velonis1 can you have a look at this?

**Comment by adrian-velonis1** [comment]
@mjaggard Thanks for your observation and precise report. The `valueComputed` field is meant for any computed value, like a function call. This may also be a column name, which is "computed" in the sense that you're "calling" on the column to fetch the values it contains instead of Liquibase reading the column name as a string (which would count as "non-computed"). I'll update our documentation to clarify this behavior.

The important part is that `valueComputed` (or `defaultValueComputed`) allows the value itself to be a function while `value` (or `defaultValue`) doesn't. For example:

```
<addColumn tableName="test_table">
    <column name="address" type="varchar(20)" defaultValue="uuid()"/>
</addColumn>
```

This corresponds to the SQL command: `ALTER TABLE test_table ADD COLUMN address VARCHAR(20) 'uuid()'`.

```
<addColumn tableName="test_table">
    <column name="address" type="varchar(20)" defaultValueComputed="uuid()"/>
</addColumn>
```

This corresponds to the SQL command: `ALTER TABLE test_table ADD COLUMN address VARCHAR(20) uuid()`.

The first example sets the new column values to the string `"uuid()"`. The second example sets the new column values to their own newly generated `uuid`. Works the same way with the `update` Change Type, etc.

BTW, you can submit a direct PR on the docs site from this repo: https://github.com/Datical/liquibase-docs. The file structure in the repo matches the URL structure of the site so you should be able to find whatever page you're using.
