### ISSUE TITLE
Mongo driver eliminates Liquibase logging

### ISSUE THREAD

**Issue by StevenMassaro** [liquibase/liquibase#3821]
## Environment

**Liquibase Version**: latest master build: 718eb6375f37ff2c215ce1e762d46cfbea98ddc6

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: N/A

**Operating System Type & Version**: Windows 10 (but probably doesn't matter)

**Infrastructure Type/Provider**: None

## Description

Putting the mongo driver in your lib directory makes logging not work at all. 

## Steps To Reproduce

Get the latest Liquibase master build.

Put the mongo driver in your lib directory. (issue occurs with https://search.maven.org/artifact/org.mongodb/mongodb-jdbc/2.0.2/jar all.jar)

Run any liquibase command with logging set at fine, and see that you get no logs.

## Actual Behavior

No logs.

## Expected/Desired Behavior

Logs.

## Additional Context
The mongo driver contains a logging.properties file that sets the handlers to an empty list. This is likely the cause of the problem.

Was originally an internal Liquibase ticket: DAT-13514

**Comment by nvoxland** [comment]
I don't see any use of `logging.properties` in our code. I was wondering if it was our CLI code that was explicitly checking for that in the classpath. But, it must be something in the general java.logging system?

**Comment by nvoxland** [comment]
The problem seems to be at https://github.com/mongodb/mongo-jdbc-driver/blob/655fdf34c83ad00348bfdd7866599c9cdb0cf35e/src/main/java/com/mongodb/jdbc/MongoDriver.java#L113 where MongoDriver explicitly reconfigures the logging when it is classloaded.

With them explicitly changing the logging setup, I don't think there's anything we can do to know the difference between "rogue" reconfiguration we want to ignore and wanted/expected reconfiguration that we want to support.

That seems like a not-commonly used and/or not very well supported driver vs the regular mongo driver?

**Comment by StevenMassaro** [comment]
> That seems like a not-commonly used and/or not very well supported driver vs the regular mongo driver?

Could very well be. [Our documentation](https://docs.liquibase.com/start/install/tutorials/mongodb.html) points to it, which sounds like an error on our part.

**Comment by MalloD12** [comment]
Closing this issue, since MondoDB [documentation](https://docsstage.liquibase.com/start/install/tutorials/mongodb.html) has been updated. Thank you, @adrian-velonis1 for making these required updates.
