### ISSUE TITLE
Feature: Don't yell

### ISSUE THREAD

**Issue by gpettey** [liquibase/liquibase#3833]
### Search first

- [X] I searched and no similar issues were found

### Description

Make the SQL generator stop yelling all the time, or at least make it optional. I do not need or want things in uppercase. None of these identifiers are quoted. The table and column names are lowercase in my XML changelog file, and those are the only things that come out in lowercase in the SQL output. In `liquibase.properties` my schema name is in lowercase, but that is turned into uppercase somewhere.

### Steps To Reproduce

1. Make a changelog for an Oracle database:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                                       https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
    <changeSet id="mytable-0" author="gpettey">
        <createTable tableName="mytable">
            <column name="id" autoIncrement="true" type="int">
                <constraints nullable="false" primaryKey="true"/>
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

2. Run `liquibase update-sql`.

### Actual Behavior

`CREATE TABLE MYSCHEMA.mytable (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL)`

### Expected/Desired Behavior

`create table schema.table (id integer generated by default as identity not null)`

### Liquibase Version

4.19.0

### Database Vendor & Version

Oracle 19c

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

WSL

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
It is a bit weird to have them all caps, but it tends to be the convention with SQL (https://softwareengineering.stackexchange.com/questions/101316/what-good-reasons-are-there-to-capitalise-sql-keywords), although it's been fading as a convention vs. when Liquibase started.

I'm going to close this issue as "won't do" since the code throughout Liquibase is like:

```        StringBuilder buffer = new StringBuilder();
        buffer.append("CREATE ");

        if (statement.getTableType() != null && statement.getTableType().trim().isEmpty()) {
            buffer.append(statement.getTableType().toUpperCase());
        }

        buffer.append("TABLE ").append(database.escapeTableName(statement.getCatalogName(),
                statement.getSchemaName(), statement.getTableName())).append(" ");
        buffer.append("(");
```
and it would take finding all the keywords (and only the keywords) throughout and changing those to lower case, without changing things that are not keywords and can be case sensitive on some database configurations such as datatypes or function names. And I don't think it's worth the potential instability to switch the casing from what is often generated from other SQL tools. 

However, if it matters enough to anyone it should be possible to add a global `liquibase.sql.keywordCase` flag that gets checked in `UnparsedSql.toSql()` and if set, runs the SQL through the `SimpleSqlGrammarTokenManager` (See SqlParser.parse()` as an example) to get the tokens and then lowercases/uppercases any `S_IDENTIFIER` tokens as it re-joins the tokens into the final sql string. 

It would add a bit of parsing overhead to every statement, but if anyone things it's important enough for them to create a PR we can re-open this issue and review the PR.
