### ISSUE TITLE
Incorrect handling of liquibase's column type 'int' in ORACLE

### ISSUE THREAD

**Issue by SIEDA-EliasHeydrich** [liquibase/liquibase#3855]
### Search first

- [X] I searched and no similar issues were found

### Description

`<column name="int_data" type="int">` produces a column of ORACLE-Type `NUMBER(38,0)`, which is incorrect.

### Steps To Reproduce

Write a changeset like this:

```
   <changeSet id="whatever" author="eheydrich">
      <createTable tableName="github_issue">
         <column name="txt_data" type="VARCHAR(10)"/>
         <column name="int_data" type="INT"/>
      </createTable>
   </changeSet>
```
and run it against an ORACLE-Database (**v19c** in my case).

### Actual Behavior

The table is created with columns of type `VARCHAR2(10)` and `NUMBER(38,0)`.

### Expected/Desired Behavior

The table should have been created with columns of type `VARCHAR2(10)` and `NUMBER(10,0)`.

### Liquibase Version

4.16.1

### Database Vendor & Version

Oracle v19c

### Additional Context

A quick explanation of `NUMBER(X,Y)` in ORACLE: The first part, the X, is called the precision. That is the number of digits in a number. It ranges from 1 to 38. The second part, the Y, is called the scale. That is the number of digits to the right of the decimal point in a number. It ranges from -84 to 127.
This means: The number 1234.56 has a precision of 6 and a scale of 2. So to store this number, you need at least a `NUMBER(6,2)`.

The meaning of a (signed) `integer` is, pretty universally, a number between −2.147.483.648 and 2.147.483.647 with no fraction. Which, in Oracle, should be a `NUMBER(10,0)`. Liquibase has decided to map its `int` to ORACLE's `INT` but that is a problem since `INT` and `SMALLINT` are just aliases in ORACLE. And they are both evaluated as `NUMBER(38)` (for whatever reason).

**Now, one could ask why this needs changing.** The answer is as follows: Liquibase's current behavior creates problems when trying to read 32bit-integer-data from such tables, as the size of the data cannot fit into a 32bit integer.
Depending on the language or tool used, inappropriate data-types are chosen due to the size and that can even introduce floating-point imprecision into reading an `int` if the employed type is e.g. some sort of double precision variant.

I am willing to fix this issue myself if someone points me to the type conversion table in the repo.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by molivasdat** [comment]
HI @SIEDA-EliasHeydrich According to Oracle's documentation an integer type has a precision of 38.
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Literals.html#GUID-F521FBA0-FFED-4079-ABC4-9052218B3FD5
An integer can store a maximum of 38 digits of precision

https://www.oracletutorial.com/oracle-basics/oracle-number-data-type/

**Comment by nvoxland** [comment]
It's an example of issues that come up between "I'm telling you what database datatype I want" vs. "I'm telling you the 'generic' datatype I want".

For oracle, "int" is a specific type with size 38. 

But other databases and other technologies define "integer" differently -- generally more like "an integer is a 32 bit number" which is smaller than oracle's. 

So when a changelog has `type="int"` what do people want us to do?

The answer to what we do isn't consistent, which is a bug on it's own. Sometimes we switch the type to "what you mean" like putting `type="text"` on mssql switches to `nvarchar(max)` even though there is actually a deprecated `text` type in mssql. But other cases (like int) we pass it along to the database as `int` vs. making sure it's equal to a 32bit integer.

For this specific issue, I think we need to close it as "won't do" because changing datatype mappings get hard for people because it makes their database structures end up different depending on the version of liquibase that did the update which is a problematic surprise. Every oracle user will have "int" types in their changelog files and so will be impacted by the change, many of who are expecting them to be number(38) types and not 32 bit integers.

@SIEDA-EliasHeydrich, if you are wanting to have a different behavior you have some options.

One is to use `number(10)` instead of `int. 

To make it a bit easier, you could define `<property name="int" value="number(10)"/>` in your changelog and then use `type="${int}` instead.

You could also create a Liquibase extension that changes the behavior. The `liquibase.datatype.core.IntType` class is what does the mapping of "int" -> "integer" so if you subclass that and register it as an extension, you can override the logic to have int -> number(10) for you specifically without impacting anyone else.

Alternately, there is the larger project of improving and standardizing the "actual" vs. "generic" datatype handling that needs to be done sometime. If you're interesting in taking on some of that project I'd be happy to talk to you about it more, @SIEDA-EliasHeydrich.

**Comment by SIEDA-EliasHeydrich** [comment]
> So when a changelog has `type="int"` what do people want us to do?
> The answer to what we do isn't consistent, which is a bug on it's own.
This is exactly the point, @nvoxland has understood the underlying issue.

In my opinion, the answer here is actually **crystal clear**: People use Liquibase for its ability to migrate database schemas and content independent of the type of DBMS, that is the selling point. Liquibase's changesets provide an abstraction that is independent of MSSQL, PostgreSQL, ORACLE, etc. One wants an abstraction because it abstracts implementation details, like how things are named and work. We expect thus that the abstraction hides all the nitty gritty stuff and provides us with an equally abstract and consistent view of the result. Therefore, it is my believe that Liquibase should always choose the, as @nvoxland puts it, "what you mean"-type because that is Liquibase's selling point.

> For this specific issue, I think we need to close it as "won't do" because changing datatype mappings get hard for people because it makes their database structures end up different depending on the version of liquibase that did the update which is a problematic surprise. Every oracle user will have "int" types in their changelog files and so will be impacted by the change, many of who are expecting them to be number(38) types and not 32 bit integers.
I have expected this because in your position, I would do the same. The risks of changing that are enormous and any pull-request make such a modification would come with gigantic caveats.

> Alternately, there is the larger project of improving and standardizing the "actual" vs. "generic" datatype handling that needs to be done sometime. If you're interesting in taking on some of that project I'd be happy to talk to you about it more, @SIEDA-EliasHeydrich.
Not under this account, no, as I am currently reporting this issue within the context of my job. However, I might contact you regarding this topic in the future, as I am a big believer in the core idea behind Liquibase...

**Comment by nvoxland** [comment]
I'll close this issue, then, since this one-off fix is not going to something we can safely do. But, we have #3325 looking for feedback and/or implementation approaches on the larger feature. Always glad to have whatever help you can provide, @SIEDA-EliasHeydrich.
