### ISSUE TITLE
Disable automatic type conversion on columns

### ISSUE THREAD

**Issue by reynico** [liquibase/liquibase#3858]
### Search first

- [X] I searched and no similar issues were found

### Description

When running a migration, Liquibase converts the column type, according to [this document](https://docs.liquibase.com/change-types/nested-tags/column.html)

So migration is defined as
```xml
            <column name="id" type="bigint" autoIncrement="true">
                <constraints primaryKey="true"/>
            </column>
```

but it tries to write it as a `BIGSERIAL` column. 

Is there any way to disable the automatic type convert?

### Steps To Reproduce

Run the migration.xml file.

### Actual Behavior

bigint column is written as bigserial.

### Expected/Desired Behavior

keep bigint as bigint.

### Database Vendor & Version

AWS Redshift

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
What is the `update-sql` that's generated for that? Since it's marked as autoIncrement="true", Liquibase will make it auto-increment which on old postgresql versions was creating it as BIGSERIAL but newer versions is BIGINT GENERATED BY DEFAULT AS IDENTITY.

Also: do you have the https://github.com/liquibase/liquibase-redshift extension installed? That may help Liquibase better understand the capabilities of redshift vs. maybe seeing it as an older version of postgresql.

**Comment by nvoxland** [comment]
Closing due to lack of response. If this is still an issue, feel free to reopen or comment.
