### ISSUE TITLE
Feature request: support '--reference-liquibase-catalog-name' and '--reference-liquibase-schema-name' parameters

### ISSUE THREAD

**Issue by TymofiiKritsak** [liquibase/liquibase#4058]
### Search first

- [X] I searched and no similar issues were found

### Description

Liquibase already supports properties:
```
--default-catalog-name
--default-schema-name

--reference-default-catalog-name
--reference-default-schema-name

--liquibase-catalog-name
--liquibase-schema-name
```

Thus, there is no support for:
```
--reference-liquibase-catalog-name
--reference-liquibase-schema-name
```

### Steps To Reproduce

There is no way to specify a separate schema and/or catalog for reference connection that is different to schema and/or catalog of the target connection.

### Expected/Desired Behavior

There is support for:
```
--reference-liquibase-catalog-name
--reference-liquibase-schema-name
```

### Liquibase Version

4.20

### Database Vendor & Version

ALL

### Liquibase Integration

NONE

### Liquibase Extensions

NONE

### OS and/or Infrastructure Type/Provider

ALL

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
These arguments would be used for:
- In diff/generate-changelog operations, how to compare knows the databasechangelog/lock table names and schemas in the reference database if they are differently named than in the target database
- In snapshot-reference, what the databasechangelog/lock table names and schemas are to skip. Currently just liquibase-catalog-name and liquibase-schema-name is used for this, so would need to deal with the case of people specifying both and failing if they are different?

Is there any other usage I'm forgetting?

**Comment by aprognimak** [comment]
Mmm yeah this is not working. As of 4.26 at least

Unexpected argument(s): --reference-liquibase-schema-name=secure
Unexpected argument(s): --output-schemas=secure

There might be others that are LISTED in --help for a command but really don't go past the args validation

**Comment by filipelautert** [comment]
Thanks for advising @aprognimak ! We will review that.

**Comment by filipelautert** [comment]
@tati-qalified are you able to reproduce it?

**Comment by aprognimak** [comment]
Ah btw just to clarify - it works when passing the config value via ENV variable or I guess liquibase.properties file would work too (again, as per the diffChangeLog --help) - there's mention in the fine logs about value pickup, but it never even gets past commandline validation if passed via cmdarg.
I am also not sure which other parameters for other commands behave like this, at least outputSchemas does for sure and unfortunately I can't build and run all the integrations at the moment.

**Comment by aprognimak** [comment]
> Hello @aprognimak - which command are you using that is showing this error? And if you try using `--referenceLiquibaseSchemaName=secure `(camel case), does it work?

Heh okay this is actually a bit more interesting, I just don't have the time to debug step-by-step, but the gist of it -

1. If I use commandline "liquibase [all arguments here, **including** command-specific args] diffChangeLog" the app spews the error about those 2 unknown parameters if present (output-schemas and reference-liquibase-schema-name). If I do not include those "unknown" parameters the thing runs fine and all the rest command-specific arguments are recognized.
2. If I use "liquibase diffChangeLog [arguments here] parameters are found and taken into consideration and stuff runs just fine

Parameter name case doesn't matter in either cases pardon the pun.

Case 1 is interesting because that's how I found this behavior - liquibase-gradle-plugin uses this to construct cmdline with which it then calls liquibase (all args first, then command name) 

Also despite --help explicitly says "command arguments come after command" it works either way just not with the parameters above, makes me think there's some commandline processing flow issue so either it should not work at all or I dunno.

Hope I'm clear, sorry about the initial confusion

**Comment by filipelautert** [comment]
> Also despite --help explicitly says "command arguments come after command" i

@aprognimak thanks for the detailed explanation, it helps a lot. Requirement for positional commands was dropped sometime ago, so seems we may have a bug parsing them (at least new commands).

**Comment by filipelautert** [comment]
@aprognimak it took me a while to navigate through the code and get the history of that . TLDR:  follow  --help directions of  "command arguments come after command" .
Long story: the parameter options that are accepted before any command like 'diffChangelog"  are listed as `global legacy commands`  and are there for backwards compatibility - new commands are not added to this list. So as output-schemas and reference-liquibase-schema-name are new parameters they need to come after diffChangelog . 
Interesting thing: there is a legacy option called --output-schemas-as that should work before the command but not after that as it got renamed to output-schemas . 

About  liquibase-gradle-plugin : this is currently under refactoring and I'm in touch with the maintainer , so will ask him to fix it if not fixed it .
