### ISSUE TITLE
incrementBy and startWith column attributes produce incorrect autoincrement clause

### ISSUE THREAD

**Issue by eugene-ivakhno** [liquibase/liquibase#4149]
### Search first

- [X] I searched and no similar issues were found

### Description

Incorrect autoincrement clause when using the following construction:
```
        <createTable tableName="test_table">
            <column name="id" type="integer" autoIncrement="true" startWith="100" incrementBy="5"/>
        </createTable>
```
It results in error with such cause: 

> syntax error at or near ","
>   Position: 92 [Failed SQL: (0) CREATE TABLE public.test_table (id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 5))],

which says that there should be no comma between those `START WITH 100` and `INCREMENT BY 5`.

### Steps To Reproduce

Execute the following changelog:
```
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    <changeSet author="me" id="test"
               logicalFilePath="empty">
        <createTable tableName="test_table">
            <column name="id" type="integer" autoIncrement="true" startWith="100" incrementBy="5"/>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

### Expected/Desired Behavior

The table should be created.

### Liquibase Version

3.6.3 but seems to be reproducible on 4.21.1 as well

### Database Vendor & Version

Postgres 15

### Liquibase Integration

maven

### Additional Context

I guess the issue is related to this code: https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java#L595

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @eugene-ivakhno , thank you for providing the section of code that's causing the error, that was really helpful!
It seems like that function is general for all databases, and currently this appears to be affecting only Postgres (it works fine with MSSQL, and MySQL simply doesn't support the incrementBy clause). 

For this bug to be fixed, a Postgres-specific function should be created in order to override the general function.

Would you like to submit a PR? If you would, and you need help, just ask and someone from our team will get in contact with you.

Thanks again!

**Comment by nicoesiea** [comment]
Hello,
I am facing a similar issue related to a table creation on MariaDB, 
I'm using the Spring boot latest version **<version>3.2.1</version>** and the bug is potentially related to this upgrade I did last week.

Here is my changeSet:
` <changeSet id="create table xxx" author="nid">
        <createTable tableName="xxx">
            <column name="id" type="bigint"><constraints primaryKey="true" nullable="false"/></column>
            <column name="reference" type="varchar(64)"/>
            <column name="description" type="varchar(128)"/>
        </createTable>
        <addAutoIncrement columnName="id" columnDataType="bigint" incrementBy="1" tableName="xxx"/>
        <createIndex tableName="xxx" indexName="idx_xxx_reference">
            <column name="reference" type="varchar(255)"/>
        </createIndex>
        <addForeignKeyConstraint constraintName="fk_xxx_other"
                                 baseTableName="xxx" baseColumnNames="other"
                                 referencedTableName="other" referencedColumnNames="id"/>
    </changeSet>`

The error message is: incrementBy="1" no more accepted MariaDB
Of course, I can remove this parameter, as MariaDB considers 1 as the default incrementation step for the auto-increment index, but this seems pretty new for me, as it was still working last week.
Is there no way to implement this parameter - as it was supposed to be as described [here](https://docs.liquibase.com/change-types/add-auto-increment.html) 

Thank you in advance
