### ISSUE TITLE
problem in rollback from version 4.22 to 4.21.1

### ISSUE THREAD

**Issue by andrebotelho-warren** [liquibase/liquibase#4289]
### Search first

- [X] I searched and no similar issues were found

### Description

My liquibase execution pipeline was using docker image with latest tag.

Some scripts were run using Liquibase version 4.22. When I rolled back to version 4.21 I started getting some errors in the liquibase status command due to a checksum difference.

![2023-05-19_15-45](https://github.com/liquibase/liquibase/assets/80538383/d067596e-6c4d-410c-aa10-9b5ad90e6aa1)

What can I do to fix this? I would like the status command to work again using version 4.21.1

### Steps To Reproduce

Since version 4.22 was deleted, I don't think we were able to reproduce.

But if possible, we would have to run a liquibase updatesql with version 4.22. And then, rollback to version 4.21.1 and try to run a liquibase status

### Expected/Desired Behavior

Perform a rollback from version 4.22 to 4.21.1

### Additional Context

https://docs.liquibase.com/start/release-notes/home.html
![image](https://github.com/liquibase/liquibase/assets/80538383/73ae7dfe-8381-470e-8060-83eab02adbcf)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @andrebotelho-warren , how are you?
This is a common issue, and it is one of the reasons why version 4.22 was removed. There are two things you can try:

**First:**
- Run clear-checksums.
- Revert to 4.21.1
- Run changelog-sync to recalculate the v8 checksums.

This will fix the checksum issue, leaving you with the prior Liquibase version.

**Second:**
Try updating to version 4.23.0 instead of reverting to 4.21.1, as this last release involves many improvements. You can see the release notes [here](https://docs.liquibase.com/start/release-notes/home.html).

I'll be closing this issue, though be sure to reopen it if the problem persists.

Have a good one!

**Comment by robert-gdv** [comment]
This might be related to #5761
