### ISSUE TITLE
Documentation missing for migrating from deprecated Liquibase.update API in v 4.24.0

### ISSUE THREAD

**Issue by sergeykad** [liquibase/liquibase#5066]
### Search first

- [X] I searched and no similar issues were found

### Description

A number of `update` methods in the `Liquibase` class were deprecated in version 4.24.0. All non-deprecated methods require a `Writer`, but I cannot find any documentation about it in the release notes or Javadoc.

### Steps To Reproduce

Switch from a previous version to 4.24.0 while using the `public void update(Contexts contexts, LabelExpression labelExpression)` and you will get a deprecation warning.

### Expected/Desired Behavior

The purpose of the additional `Writer` parameter in the update APIs will be documented and the release notes will document the breaking change and how to migrate.
As it is I am not sure what this parameter is for and what I should pass to it.

### Liquibase Version

4.24.0

### Database Vendor & Version

any

### Liquibase Integration

Java API

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@sergeykad Thank you for the feedback. We have been updating the Liquibase API and have fallen behind on our documentation. I'll work with the development team to update the API docs and let you know when it's available.

**Comment by MalloD12** [comment]
Hi @sergeykad,

Yeah, as you have seen we have already deprecated several methods from Liquibase API  and we intend to keep deprecating more things from there until we remove it in a future version. As you can see in the Javadoc of some of the deprecated methods we are recommending people to use the `ComandScope` way (updated Command Framework) to know how to run different command methods. 

At the moment, we are doing some updates to this [page](https://contribute.liquibase.com/extensions-integrations/integration-guides/calling-commands/). Here we will be showing some different ways of writing methods to execute a given command. For example, for calling `update` command by making use of a writer to use for command results we can use `setOutput()` as shown below:
``` java
CommandScope updateCommand = new CommandScope(UpdateSqlCommandStep.COMMAND_NAME);
updateCommand.addArgumentValue(DbUrlConnectionCommandStep.DATABASE_ARG, getDatabase());
updateCommand.addArgumentValue(UpdateSqlCommandStep.CHANGELOG_FILE_ARG, changeLogFile);
updateCommand.addArgumentValue(DatabaseChangelogCommandStep.CHANGELOG_ARG, databaseChangeLog);
updateCommand.addArgumentValue(UpdateSqlCommandStep.CONTEXTS_ARG, contexts != null ? contexts.toString() : null);
updateCommand.addArgumentValue(UpdateSqlCommandStep.LABEL_FILTER_ARG, labelExpression != null ? labelExpression.getOriginalString() : null);
updateCommand.addArgumentValue(ChangeExecListenerCommandStep.CHANGE_EXEC_LISTENER_ARG, changeExecListener);
updateCommand.addArgumentValue(DatabaseChangelogCommandStep.CHANGELOG_PARAMETERS, changeLogParameters);
updateCommand.setOutput(new WriterOutputStream(output, GlobalConfiguration.OUTPUT_FILE_ENCODING.getCurrentValue()));
updateCommand.execute();
```  
Thanks,
Daniel.

**Comment by lily-es** [comment]
Would be nice with some more detailed documentation, or a proper migration guide for this. At the moment we create a Liquibase object, passing it a changelog file and a db connection already configured with all the necessary credentials and other configuration. I cannot see how we can make use of this at the moment using the new CommandScopes.

```kotlin
        val uri = "......" //We define the db uri here
        val properties = Properties()
        //We set some properties here such as username, password, driver configuration

        DriverManager.getConnection(uri, properties).use { connection ->
            val liquibase = Liquibase(
                "db.changelog/db.changelog-master.xml",
                ClassLoaderResourceAccessor(),
                JdbcConnection(connection)
            )

            liquibase.update("")
        }
```

**Comment by MalloD12** [comment]
Hi @lily-es,

We have recently added some extra examples to this [page](https://contribute.liquibase.com/extensions-integrations/integration-guides/calling-commands/). These changes have been merged, but have not yet been released. They could be available in a week or so. 

Liquibase object has most of its methods `@deprecated` and we are aiming to keep deprecating things from there and removing this class in the future. There is no relationship between `Liquibase` and `CommandScope` object, so whatever you assign as an argument to one of them it won't be available to the other. So having something like the code below should work:


``` java
CommandScope updateCommand = new CommandScope(UpdateCommandStep.COMMAND_NAME);
            updateCommand.addArgumentValue(DbUrlConnectionCommandStep.DATABASE_ARG, getDatabase());
            updateCommand.addArgumentValue(UpdateCommandStep.CHANGELOG_FILE_ARG, changeLogFile);
            updateCommand.addArgumentValue(UpdateCommandStep.CONTEXTS_ARG, <context_var>);
            updateCommand.addArgumentValue(UpdateCommandStep.LABEL_FILTER_ARG, <label_var);          
            updateCommand.execute();
```

Thanks,
Daniel.

**Comment by Djaytan** [comment]
Hello,

Before all, sorry if that's not the right place to speak about that.

Actually I'm completely disappointed about the new architectural choice. The API is just not convenient at all to use... And that's without mentioning the fact that migrating is even less obvious that it should be.

The previous API was too low level IMO and thus a bit hard to manipulate... Especially when our use cases are the basic ones and are not supposed to require too much effort. Ok, there is an integration with Spring Boot framework and CDI... But what about if we don't rely on neither of the solutions? Like with Guice for example... We have to develop a integration solution ourselves... By dealing with a low-level API... And copying what has been done for other integrations...
There is clearly an issue on the API side, and I have the feeling that the current move is making the things even more crazy... Even if the idea to try improving the situation was a good thing initially.

When having a look on Flyway side, the API is a lot more convenient to use. On Liquibase, creating a command in order to execute it just after... It's weird! And in fact it doesn't solve the fact that the API is too low level.
Have a look on Flyway side, and look the difference.

I don't write this whole comment because I want to blame you or anything else. You made such a great job in making this library. It has a really high potential and can outpace Flyway a lot with its database agnostic approach! But I really think tha

**Comment by Djaytan** [comment]
Hello,

Before all, sorry if that's not the right place to speak about that.

Actually I'm completely disappointed about the new architectural choice. The API is just not convenient to use at all... And that's without mentioning the fact that migrating is even less obvious that it should be.

The previous API was too low level IMO and thus a bit hard to manipulate... Especially when our use cases are the basic ones and are not supposed to require too much effort when implementing on our side. Ok, there is an integration with Spring Boot framework and CDI... But what about if we don't rely on neither of the solutions? Like with Guice for example... We have to develop an integration solution ourselves... By dealing with a low-level API... And copying what has been done for other integrations...
Doing things differently would permit to integration the API in any system easily without having to repeat code accross integration implementations like it's the case today.

Another aspect that hit me is the fact that an API has been deprecated for external consumers... But is still used internally by integration solutions (e.g. `SpringLiquibase`). So we can't just get inspiration from there to use the new API. And well, it gave the feeling that the change has been made too eagerly and incompletely. Fortunately you are pushing efforts on improving the documentation, that's a great thing a thank you for that since it's clearly a welcome help for us.

But well, by making it short, there is clearly an issue on the API side, and I have the feeling that the current move is making the things even more crazy... Even if the idea to try improving the situation was a good thing initially.

When having a look on Flyway side, the API is a lot more convenient to use. You just have to gather all configuration values that the tool need, pass them with minimal efforts and that's it! No need to create `Database` object which may requires a `JdbcConnection` and so on... Just a standard `DataSource` and that's it for JDBC use cases. Yes for more advanced use cases a user may have to create a `Database` object, but I guess a good proportion of users may start with an SQL database like it's my case with a first basic solution. But take this example only as an example: I don't know all the use cases that an API consumer may have, you better know than me.

I don't write this whole comment because I want to blame you or anything else. You made such a great job in making this library. It has a really high potential and can outpace Flyway a lot with its database agnostic approach! But having such bad API (sorry for being as direct as that, but I really think so) can provide bad signs for the underlying implementation and thus dissuade new developers to use the library :/
And well, that provide so much pain for us whereas doing things differentielly could solve that easily while reducing your maintenances efforts: two great things tackled at the same time, and not small ones!

What do you think?

I hope you understood my point of view, and anyway thank you a lot for sharing this library and pushing efforts on improving it everyday.

**Comment by lily-es** [comment]
> Hello,
> 
> Before all, sorry if that's not the right place to speak about that.
> 
> Actually I'm completely disappointed about the new architectural choice. The API is just not convenient to use at all... And that's without mentioning the fact that migrating is even less obvious that it should be.
> 
> The previous API was too low level IMO and thus a bit hard to manipulate... Especially when our use cases are the basic ones and are not supposed to require too much effort when implementing on our side. Ok, there is an integration with Spring Boot framework and CDI... But what about if we don't rely on neither of the solutions? Like with Guice for example... We have to develop an integration solution ourselves... By dealing with a low-level API... And copying what has been done for other integrations... Doing things differently would permit to integrate Liquibase in any system easily without having to repeat code accross integration implementations like it's the case today.
> 
> Another aspect that hit me is the fact that an API has been deprecated for external consumers... But is still used internally by integration solutions (e.g. `SpringLiquibase`). So we can't just get inspiration from there to use the new API. And well, it gave the feeling that the change has been made too eagerly and incompletely. Fortunately you are pushing efforts on improving the documentation, that's a great thing a thank you for that since it's clearly a welcome help for us.
> 
> But well, by making it short, there is clearly an issue on the API side, and I have the feeling that the current move is making the things even more crazy... Even if the idea to try improving the situation was a good thing initially.
> 
> When having a look on Flyway side, the API is a lot more convenient to use. You just have to gather all configuration values that the tool need, pass them with minimal efforts and that's it! No need to create `Database` object which may requires a `JdbcConnection` and so on... Just a standard `DataSource` and that's it for JDBC use cases. Yes for more advanced use cases a user may have to create a `Database` object, but I guess a good proportion of users may start with an SQL database like it's my case with a first basic solution. But take this example only as an example: I don't know all the use cases that an API consumer may have, you better know than me.
> 
> I don't write this whole comment because I want to blame you or anything else. You made such a great job in making this library. It has a really high potential and can outpace Flyway a lot with its database agnostic approach! But having such bad API (sorry for being as direct as that, but I really think so) can provide bad signs for the underlying implementation (which could be a mess) and thus dissuade new developers to use the library (fear of bugs... And when seeing 500 opened issues... It doesn't improve the situation as well) :/ And well, that provide so much pain for us whereas doing things differentielly could solve that easily while reducing your maintenances efforts: two great things tackled at the same time, and not small ones!
> 
> What do you think?
> 
> I hope you understood my point of view, and anyway thank you a lot for sharing this library and pushing efforts on improving it everyday.

I have to agree. The new API feels very unintuitive and complicated to work with. The way to configure it is non-standard as well (if I already have a Connection with all the properties that I need, why cant I just use that?). The lack of documentation from the outset for such a big and confusing change is also dissapointing, and makes the release feel rushed. Obviously its good that its being worked on, but I still have no idea how to migrate my code. Something like a proper migration guide would have been amazing here. I'm hoping that the documentation improves so I can i migrate to the new API instead of using the deprecated one, but I do feel like this new API is more complex and much more opaque.

**Comment by fatihdogmus** [comment]
I also have to agree. The new API is very unintuitive to use, compared to something like Liquibase or SpringLiquibase classes. It is very inconvenient to use them in a reusable manner. It might be convenient to use them internally, but we need higher level APIs. They can stay like this, but I think we need higher level abstractions for general use.
