### ISSUE TITLE
Chacksum for the changeset containing NEXTVAL expression fails on second update (PostgreSQL) 

### ISSUE THREAD

**Issue by manunin** [liquibase/liquibase#5521]
### Search first

- [X] I searched and no similar issues were found

### Description

On PostgreSQL when the changeset contains NEXTVAL construction with a dot like the following 
`<column name="ID" valueComputed="S_WEB_LOCALE.NEXTVAL"/>` 
it's applied correctly on updating after dropAll, and fails with checksum error on the second update

### Steps To Reproduce

1. Create a table and sequence on PostgreSQL
2. Run liquibase update for the changeset like:  

`<changeSet id="2023-12-18_14:26:23" author="Autor" context="online">
        <insert tableName="SOME_TABLE">
            <column name="ID" valueComputed="S_SOME_TABLE.NEXTVAL"/>
        </insert>
        <rollback/>
    </changeSet>`

4. Update completes successfully
5. Run liquibase update the second time (on existing data)
6. Error with checksum appears

The main cause is that on the first update, liquibase converts S_SOME_TABLE.NEXTVAL to NEXTBAL('S_SOME_TABLE') and calculates checksum from converted value, and on the second update original S_SOME_TABLE.NEXTVAL is taken for checksum check.

### Expected/Desired Behavior

Liquibase doesn't fail on the second update.

### Liquibase Version

4.25.1

### Database Vendor & Version

PostgreSQL 12

### Liquibase Integration

maven

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @manunin 
By chance do you have an Oracle-Postgres compatibility mode turned on?
The first syntax you specified, `S_WEB_LOCALE.NEXTVAL`, is Oracle syntax, not Postgres. 

Using Postgres and running `liquibase update-sql` with the changeset you provided, I never got the correct syntax - only the Oracle one. If your environment is set up in a way that can convert Oracle syntax into Postgres, that might explain why it's working the first time you run `liquibase update`.

When re-running `liquibase update`, Liquibase calculates checksums based on the changesets themselves, and not the generated SQL, which is why there's a checksum mismatch.

To resolve this, modify your changeset to use the correct expression in the `valueComputed` attribute:
`<column name="ID" valueComputed="S_WEB_LOCALE.NEXTVAL"/>`

I hope this helps, but let me know if you have any other questions.
Thank you,
Tatiana
