### ISSUE TITLE
RunAlways with runOnChange and preconditions fails on 4.27

### ISSUE THREAD

**Issue by alomine** [liquibase/liquibase#5798]
### Search first

- [X] I searched and no similar issues were found

### Description

Hello,
I just updated liquibase from version 4.17.2 to 4.27 and im facing some issues. There are some changesets which have runOnChange="true" and runAlways="true" plus some preconditions. Preconditions fails as sqlChecks does not return expected result which is fine but it tries to insert value into databasechangelog second time which results in:

> [2024-04-15 08:36:23] WARNING [liquibase.command] Update command encountered exception
> liquibase.exception.LiquibaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ORA-00001: unique constraint violated (PK_DATABASECHANGELOG)
>  [Failed SQL: (1) INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID)

### Steps To Reproduce

When table exists and preconditions fail it tries to insert into databasechangelog second time

```
    <changeSet id="SOME_ID" author="SOME_AUTHOR" runOnChange="true" runAlways="true">
        <preConditions onFail="MARK_RAN">
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM user_objects WHERE object_type IN ('TABLE', 'VIEW') AND object_name = 'TAB_NAME'
            </sqlCheck>
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM config where value='config1';
            </sqlCheck>
        </preConditions>
        <createTable tableName="TAB_NAME">
            <column name="ID" type="NUMBER(14)" />
        </createTable>
    </changeSet>
```

	

### Expected/Desired Behavior

Liquibase should not insert same value into databasechangelog second time

### Liquibase Version

4.27

### Database Vendor & Version

Oracle 19.12

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by alomine** [comment]
**UPDATE**
The issue was that I had primary key on "ID", "AUTHOR", "FILENAME". I did some tests right now and it seems that liquibase now is generating new row each time such changeset runs. Is this new feature ?

**Comment by tati-qalified** [comment]
Hi @alomine, the reason why a new row is generated on your DBCL table each time you run `liquibase update` is that the precondition has the attribute `onFail="MARK_RAN"`. This means that Liquibase will log the changeset as ran, along with the date it was executed and the order of execution. If you don't want this to happen, you can change it to `onFail="CONTINUE"`. The execution will be the same, except the execution won't be logged in the DBCL table.


> The issue was that I had primary key on "ID", "AUTHOR", "FILENAME"

This makes sense, because each log will have the same values for those three columns, but it will differ in "DATEEXECUTED", "ORDEREXECUTED" and, only once, in "EXECTYPE". If you want to keep marking that changeset as "MARK_RAN", you should remove or modify your primary key.


Side note: I noticed that you have written `runOnChange="true" runAlways="true"` - this isn't the best practice, as you appear to want it to run when it is changed, but it will also run every time you execute `liquibase update`. It's not a problem by itself, but it might cause you trouble in the future.

Hope this helps, let me know if you have any other questions.
Tatiana

**Comment by alomine** [comment]
Hello! Thanks for response. The need of using both `runOnChange="true" runAlways="true"` comes from running scripts in sql files. As far as I remember `runAlways=true` wasn't working as scripts were often changed and in result we got validation error as md5sum changed. Yes, we could use only `runOnChange="true"` but in such sqlfiles md5sum happened to be calculated wrong so no change was detected even if file was changed. 
No we are trying to test new version (seems like md5sum for sqlfiles changed) but im just wondering if those new rows in DBCL is something new since version 4.17? Then, back in 4.17 only one row was created per ID, AUTHOR, FILENAME. Thats my true question here

**Comment by tati-qalified** [comment]
@alomine currently, only one row is created per `ID+AUTHOR+FILENAME+ORDEREXECUTED+EXECTYPE`.
If the precondition is configured with `onFail="MARK_RAN"`, each new run will generate a new `ORDEREXECUTED`, which will create a new primary key and add another row to the table.

Let me know if you have any other questions.
Tatiana

**Comment by JonBetts** [comment]
Hi there,

I actually just came across the same issue when upgrading from 4.20 to 4.30. Setting the `preCondition` to `onFail=CONTINUE` as suggested does resolve it, so thanks for that. However, as @alomine says, when did this actually change? I've never had an issue until now, and nothing has changed in my database. Those changesets have been around for a few years, and Liquibase has never wanted to create more than one entry for them in the DBCL table. Would be good to know exactly where this changed for future reference.

Thank you in advance.

**Comment by tati-qalified** [comment]
Hi @JonBetts, do you have a primary key on the DBCL table for  "ID"+"AUTHOR"+"FILENAME"? This was the cause of the error originally, as now Liquibase uses more columns for its DBCL primary key.

If you haven't created your own primary key, it should work fine, so I'd need some more information on the changes you're running in order to assist you.

**Comment by JonBetts** [comment]
Yes I do have those columns as the primary key. Do you know what Liquibase version changed the primary key, and do you have a commit reference for it please? I don't really want multiple entries in the databasechangelog every time a `runAlways` changeset has been run. Is there a way to stop it other than using `onFail=continue`? The problem with using that is it won't ever add a record to the DBCL table then. I guess I'll just have to decide if I want no entries or a new entry every time!

Many thanks.

**Comment by tati-qalified** [comment]
@JonBetts It was introduced by [this PR](https://github.com/liquibase/liquibase/commit/25faec4fc236cf9455392fd4f1b90fa504ec8bc5) in version 4.21.0. 
Up until 4.20.0, using `onFail=MARK_RAN` would set `EXCECTYPE` to `RERAN`. Since 4.21.0, it will only be set to `RERAN` if the changeset was actually executed. If not, it will be set to `MARK_RAN`.
This causes the behaviour we've discussed. If you wish, you can download and modify the source code (as it's a simple change) to generate your own `liquibase-core.jar` file.
