### ISSUE TITLE
loadData for csv file with name column

### ISSUE THREAD

**Issue by stegra23** [liquibase/liquibase#6078]
### Search first

- [X] I searched and no similar issues were found

### Description

If you want to use Liquibase loadData for a CSV file and there is a column 'name' you get the following error.
Liquibase is searching for a file 'Afghanistan' which is content of the CSV file.
If you import a CSV file without a column 'name' everything is working.

ERROR: Exception Primary Class:  FileNotFoundException
ERROR: Exception Primary Reason:  The file Afghanistan was not found in the configured search path:
...
2024-07-06 14:50:09.957 SEVERE liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase.xml::2024-07-06_0001::stegra:
     Reason: liquibase.exception.DatabaseException: The file Afghanistan was not found in the configured search path:
...
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase.xml::2024-07-06_0001::stegra:
...
More locations can be added with the 'searchPath' parameter.
	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:345)
	at liquibase.statement.ExecutablePreparedStatementBase.attachParams(ExecutablePreparedStatementBase.java:217)
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:117)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:175)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1176)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:768)
...
Caused by: java.io.FileNotFoundException: The file Afghanistan was not found in the configured search path:
...
More locations can be added with the 'searchPath' parameter.
	at liquibase.resource.ResourceAccessor.getExisting(ResourceAccessor.java:222)
	at liquibase.statement.ExecutablePreparedStatementBase.getResourceAsStream(ExecutablePreparedStatementBase.java:479)
	at liquibase.statement.ExecutablePreparedStatementBase.toCharacterStream(ExecutablePreparedStatementBase.java:435)
	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:338)

### Steps To Reproduce

Content of data/countries_iso_3166.csv:
id,name,alpha_2,alpha_3
4,Afghanistan,AF,AFG

Liquibase changeSet:
```
<changeSet author="stegra" id="2024-07-06_0001">
<loadData encoding="UTF-8" relativeToChangelogFile="true" file="data/countries_iso_3166.csv"
	separator="," schemaName="public" tableName="country">
</loadData>
</changeSet>
```

Java code:
Scope.child(
		Map.of(Scope.Attr.resourceAccessor.name(),
				new ClassLoaderResourceAccessor(getClass().getClassLoader())),
		() -> new CommandScope("update")
				.addArgumentValue(DbUrlConnectionArgumentsCommandStep.DATABASE_ARG, database)
				.addArgumentValue(UpdateCommandStep.CHANGELOG_FILE_ARG, LIQUIBASE_CHANGELOG)
				.addArgumentValue(DatabaseChangelogCommandStep.CHANGELOG_PARAMETERS,
						new ChangeLogParameters(database))
				.execute());

### Expected/Desired Behavior

A 'name' column should be treated as every other column.

### Liquibase Version
4.28.0

### Database Vendor & Version

PostgreSQL 16.3.0

### Liquibase Integration

Java

### OS and/or Infrastructure Type/Provider

Ubuntu 24.04

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @stegra23, thank you for reporting this issue. We recently had another user mentioning a similar bug: #6068. Note that the cause is different but the behaviour is the same.

However, I was unable to replicate your issue. I tried using both the CLI and the Java API, with the code you've provided.
The OS might have something to do with it, as I'm using Windows, but otherwise I'm not sure why it's not replicable.

Would you be able to provide a minimum reproducer project?

Thank you,
Tatiana

**Comment by stegra23** [comment]
Hi @tati-qalified ,
ok, I have try this here:
https://github.com/stegra23/liquibase.issue6078
The issue only occurs with Postgresql but not with H2. See main methods in classes Postgresql and H2.
Thus you need a postgresql database stegra2 or change the JDBC_CONNECTION_URL in the class Postgresql.
Thx
Stephan

**Comment by tati-qalified** [comment]
Hi @stegra23, thank you for providing your code.
I've managed to track the error down. When executing `loadData`, Liquibase first finds the table properties (column names, data types, etc.) and parses the CSV file.
It then iterates over the CSV rows and over those rows' columns, always keeping their properties. For the most part, your "name" column is correctly interpreted as having type "clob", which is compatible with type "text".

 In the `applyColumnParameter` function inside `ExecutablePreparedStatementBase.java`, for some reason, the column passed as a parameter now is of type "clobFile" instead of "clob". Then, as it's treated as a file, Liquibase tries to find it in the project, classpath, searchpath, etc. and obviously doesn't find it. This object should have its "value" attribute set to something other than `null`
![image](https://github.com/user-attachments/assets/96fdce41-f497-4e4a-92ed-7c85baa814e3)


If you look at the `if` statement [here](https://github.com/liquibase/liquibase/blob/e854a6e18c29651da0d51265a28c58f22ef3248b/liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java#L240), you can see that this is where the execution go into:
```
if (col.getValue() != null) {
            LOG.fine("value is string/UUID/blob = " + col.getValue());
            if (col.getType() != null && col.getType().equalsIgnoreCase(LoadDataChange.LOAD_DATA_TYPE.UUID.name())) {
                stmt.setObject(i, UUID.fromString(col.getValue()));
            } else if (col.getType() != null && col.getType().equalsIgnoreCase(LoadDataChange.LOAD_DATA_TYPE.OTHER.name())) {
                stmt.setObject(i, col.getValue(), Types.OTHER);
            } else if (LoadDataChange.LOAD_DATA_TYPE.BLOB.name().equalsIgnoreCase(col.getType())) {
                stmt.setBlob(i, new ByteArrayInputStream(Base64.getDecoder().decode(col.getValue())));
            } else if (LoadDataChange.LOAD_DATA_TYPE.CLOB.name().equalsIgnoreCase(col.getType())) {
                try {
                    if (database instanceof PostgresDatabase || database instanceof SQLiteDatabase) {
                        // JDBC driver does not have the .createClob() call implemented yet
                        stmt.setString(i, col.getValue());
                    } else {
                        Clob clobValue = stmt.getConnection().createClob();
                        clobValue.setString(1, col.getValue());
                        stmt.setClob(i, clobValue);
                    }
                } catch (SQLFeatureNotSupportedException e) {
                    stmt.setString(i, col.getValue());
                }
            } else {
                stmt.setString(i, col.getValue());
            }
```


@balczer-dominik this is the same thing that is happening in the issue you reported, as `longtext` is also considered a `clob` type.

Would any of you be willing to submit a PR in order to fix this? Our development team would be available to provide any guidance needed.

Thank you!
Tatiana
