### ISSUE TITLE
Liquibase hangs when trying to apply changesets on a newly created machine

### ISSUE THREAD

**Issue by daniel-gray-jemmic** [liquibase/liquibase#6178]
### Search first

- [X] I searched and no similar issues were found

### Description

Applying a large amount of Liquibase changesets from a newly created machine (like a fresh VM/Docker container) leaves the process hanging and making very little progress.

### Steps To Reproduce

Launch a Liquibase changeset application (with a large-ish number of changes) from a fresh VM/container, and it will hang for what seems forever, checking the `/proc/sys/kernel/random/entropy_avail` shows that it is regularly at 0 during the hang.

### Expected/Desired Behavior

Liquibase should not hang, it should apply the changesets normally.

### Liquibase Version

4.29

### OS and/or Infrastructure Type/Provider

Ubuntu (but most Linux would probably be affected too)

### Additional Context

The culprit seems to be 3daa688c6a99ed131687036ba4e40cd743c4b3c8, where the SecureRandom was moved to use the Apache Commons RandomStringUtils. This probably drained the entropy faster than the initial solution. I'm aware that this change was done to improve performance of the Scope ID generation, so I will send a PR that should perform better than SecureRandom and not have this entropy problem. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by rd-henning-ellerweg** [comment]
Maybe this is related, so thats why i comment here. I also had the problem of hanging liquibase changes which seemed at the time to be related to 4.29. However, I discovered that actually commons-lang3 dependedency management uses 3.16.0 in my project. Forcing 3.14 resolved the issue with hanging liquibase. No clue why though 
As of now liquibase-core dependencies use 3.14 according to the dependency tree.

**Comment by danielthegray** [comment]
Yes, this is absolutely related. So what happened is:
1. The Apache Commons team decided that they want to be "Secure By Default" and moved the default implementation of `RandomStringUtils` from using `ThreadLocalRandom` (fast and non-blocking) to `SecureRandom.getInstanceStrong()`, the strongest random number generator, which **also blocks arbitrarily when the system runs out of entropy**. Never mind that just using the default `SecureRandom` would have been a better "secure default" (since it at least doesn't block), although I would also be deeply opposed to just pushing a 20x performance hit on everybody (yes, it's that much slower).
2. If you happened to update to the latest Apache Commons, the conflict resolution mechanism would make Liquibase also use the latest version with the change to `SecureRandom.getInstanceStrong()` and cause the block.

I've sent a PR (https://github.com/liquibase/liquibase/pull/6179) that resolves this issue and explicitly uses ThreadLocalRandom (since it is being used to generate random execution Scope IDs). Once it's merged, it shouldn't matter what version of Apache Commons is merged in, as RandomStringUtils will not be used anymore.

**Comment by famod** [comment]
Related: #6156

**Comment by filipelautert** [comment]
Fixed by https://github.com/liquibase/liquibase/pull/6179 , thanks @danielthegray !

**Comment by dpanas-sollers** [comment]
IMPORTANT NOTE: this problem can also be related to WSL2!  

If you use WSL2 and you run liquibase from path mounted to it (like /mnt/c/path-to-liquibase-changeset) then you will also face this no matter which version you use.  
In my case  (chagelog-master.xml includes ~2500 files) up to 4.16.1 all works fine, update takes ~20min (various versions from 3.6.0 and up).  
From 4.17 the process takes arround ~4h!!! For example with 4.29.2 which includes your fix @danielthegray it ended after ... 268 minutes (~4.5h) !!  But when i copy my changesets to ~/ folder (ex. /hom/user/my-changesets) then it runs as usual - ~19min

It seems like (please someone confirm this) verison 4.17 and newer introduce file validation. And since WSL2 mountings are known to have atrocious performance, with large number of files (~2500 in my case) this problem will hit you even harder.

**Comment by filipelautert** [comment]
> It seems like (please someone confirm this) verison 4.17 and newer introduce file validation. And since WSL2 mountings are known to have atrocious performance, with large number of files (~2500 in my case) this problem will hit you even harder.

@dpanas-sollers you are correct, in 4.17 liquibase IO operations were completely revamped . Are you using a recent version of java (17, 21) or still with 8? Maybe it's related to the use of "new" `nio` libraries?
